// Generated by mana-compiler from tests/or_simple_test.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"


mana::Result<int32_t, std::string> get_result();
int32_t test();

mana::Result<int32_t, std::string> get_result() {
    return mana::Ok(42);
}

int32_t test() {
    int32_t x = [&]() {
        auto __or_0 = get_result();
        if (__or_0.is_ok()) return __or_0.unwrap();
        return 0;
    }();
    return x;
}

int32_t main() {
    mana::println(test());
    return 0;
}

