// Generated by mana-compiler from C:\dev\mana-lang\tests\semicolon_minimal_test.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"



int32_t main() {
    int32_t x = 10;
    x = (x + 1);
    mana::println(x);
    return 0;
}

