// Generated by mana-compiler from tests/vnext_phase2_test.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"


int32_t test_when(int32_t x);

int32_t test_when(int32_t x) {
    int32_t result = [&]() {
        auto __match_value_0 = x;
        if (__match_value_0 == 0) return 100;
        if (__match_value_0 == 1) return 200;
        return 300;
    }();
    return result;
}

int32_t main() {
    int32_t val = test_when(42);
    mana::println(val);
    return 0;
}

