// Generated by mana-compiler from tests/vnext_phase4_test.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"



int32_t main() {
    std::string name = "World";
    int32_t age = 42;
    float pi = 3.1400000000000001;
    mana::println("Single arg test");
    ([&]{ std::cout << "Hello, "; std::cout << name; std::cout << "!"; std::cout << std::endl; }());
    ([&]{ std::cout << "Age: "; std::cout << age; std::cout << ", Pi: "; std::cout << pi; std::cout << std::endl; }());
    ([&]{ std::cout << "Mixed: "; std::cout << 1; std::cout << " "; std::cout << 2.5; std::cout << " "; std::cout << true; std::cout << std::endl; }());
    mana::print("No newline: ");
    mana::println(123);
    return 0;
}

