// Generated by mana-compiler from C:\dev\mana-lang\tests\vnext_phase5_test.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"


int32_t add(int32_t a, int32_t b);

int32_t add(int32_t a, int32_t b) {
    return (a + b);
}

int32_t main() {
    int32_t x = 10;
    int32_t y = 20;
    std::string name = "World";
    float PI = 3.1400000000000001;
    x = 15;
    x = (x + 5);
    y = (y - 3);
    x = (x + 1);
    y = (y - 1);
    ([&]{ std::cout << "Hello, "; std::cout << name; std::cout << "!"; std::cout << std::endl; }());
    ([&]{ std::cout << "x = "; std::cout << x; std::cout << ", y = "; std::cout << y; std::cout << std::endl; }());
    ([&]{ std::cout << "sum = "; std::cout << add(x, y); std::cout << std::endl; }());
    if ((x > 10)) {
        mana::println("x is big");
    }
    int32_t i = 0;
    while ((i < 3)) {
        ([&]{ std::cout << "i = "; std::cout << i; std::cout << std::endl; }());
        i = (i + 1);
    }
{
        int32_t j = 0;
        while ((j < 3)) {
            ([&]{ std::cout << "j = "; std::cout << j; std::cout << std::endl; }());
            j = (j + 1);
        }
    }    for (int32_t k = 0; k < 3; ++k) {
        ([&]{ std::cout << "k = "; std::cout << k; std::cout << std::endl; }());
    }
    return 0;
}

