// Generated by mana-compiler from tests/vnext_phase1_test.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"


enum class Color {
    Red,
    Green,
    Blue
};

void test_type_aliases();

void test_type_aliases() {
    int64_t x = 42;
    double y = 3.1400000000000001;
    mana::println(x);
}

int32_t main() {
    test_type_aliases();
    mana::println("vNext Phase 1 test passed!");
    return 0;
}

