// Generated by mana-compiler from tests/vnext_phase3_test.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"


mana::Result<int32_t, std::string> get_result(bool success);
int32_t test_or_return();
int32_t test_or_block();

mana::Result<int32_t, std::string> get_result(bool success) {
    if (success) {
        return mana::Ok(42);
    }
    return mana::Err("failed");
}

int32_t test_or_return() {
    int32_t value = [&]() {
        auto __or_0 = get_result(true);
        if (__or_0.is_ok()) return __or_0.unwrap();
        return 0;
    }();
    return value;
}

int32_t test_or_block() {
    int32_t value = [&]() {
        auto __or_1 = get_result(false);
        if (__or_1.is_ok()) return __or_1.unwrap();
        mana::println("Error occurred, returning default");
        return (-1);
    }();
    return value;
}

int32_t main() {
    int32_t result1 = test_or_return();
    mana::println(result1);
    int32_t result2 = test_or_block();
    mana::println(result2);
    return 0;
}

