// Generated by mana-compiler from c:/dev/mana-lang/tests/playground/hello_world.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"



int32_t main() {
    mana::println("Hello, Mana!");
    return 0;
}

