// Generated by mana-compiler from c:/dev/mana-lang/tests/playground/iterators.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"



int32_t main() {
    mana::println("Counting 0 to 4:");
    for (int32_t i = 0; i < 5; ++i) {
        ([&]{ std::cout << "  "; std::cout << i; std::cout << std::endl; }());
    }
    std::array<int32_t, 5> numbers = {10, 20, 30, 40, 50};
    int32_t sum = 0;
    for (auto n : numbers) {
        sum = (sum + n);
    }
    ([&]{ std::cout << "Sum of array:"; std::cout << sum; std::cout << std::endl; }());
    mana::println("Multiplication table 1-3:");
    for (int32_t i = 1; i < 4; ++i) {
        for (int32_t j = 1; j < 4; ++j) {
            int32_t product = (i * j);
            ([&]{ std::cout << "  "; std::cout << i; std::cout << " x "; std::cout << j; std::cout << " = "; std::cout << product; std::cout << std::endl; }());
        }
    }
    return 0;
}

