// Generated by mana-compiler from c:/dev/mana-lang/tests/playground/loops.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"



int32_t main() {
    int32_t i = 0;
    int32_t sum = 0;
    while ((i < 5)) {
        sum = (sum + i);
        i = (i + 1);
    }
    ([&]{ std::cout << "Sum of 0..4: "; std::cout << sum; std::cout << std::endl; }());
    int32_t count = 3;
    while ((count > 0)) {
        ([&]{ std::cout << "Countdown: "; std::cout << count; std::cout << std::endl; }());
        count = (count - 1);
    }
    mana::println("Liftoff!");
    return 0;
}

