// Generated by mana-compiler from c:/dev/mana-lang/tests/playground/structs.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"


struct Point {
    double x;
    double y;
};


Point Point_new(double x, double y) {
    return Point{.x = x, .y = y};
}

double Point_distance(Point& self, Point other) {
    float dx = (self.x - other.x);
    float dy = (self.y - other.y);
    return std::sqrt(((dx * dx) + (dy * dy)));
}

int32_t main() {
    Point p1 = Point_new(0.0, 0.0);
    Point p2 = Point_new(3.0, 4.0);
    ([&]{ std::cout << "Distance: "; std::cout << Point_distance(p1, p2); std::cout << std::endl; }());
    return 0;
}

