// Generated by mana-compiler from c:/dev/mana-lang/tests/playground/variants.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"


struct Shape_Circle {
    double _0;
};

struct Shape_Rectangle {
    double _0;
    double _1;
};

enum class ShapeTag {
    Circle,
    Rectangle,
    Point
};

struct Shape {
    ShapeTag tag;
    std::variant<std::monostate, Shape_Circle, Shape_Rectangle> data;

    static Shape Circle(double v0) {
        return Shape{ShapeTag::Circle, Shape_Circle{v0}};
    }
    static Shape Rectangle(double v0, double v1) {
        return Shape{ShapeTag::Rectangle, Shape_Rectangle{v0, v1}};
    }
    static Shape Point() {
        return Shape{ShapeTag::Point, std::monostate{}};
    }
};

double area(Shape shape);

double area(Shape shape) {
    return [&]() {
        auto __match_value_0 = shape;
        if (__match_value_0.tag == ShapeTag::Circle) {
            auto __data_0 = std::get<Shape_Circle>(__match_value_0.data);
            auto r = __data_0._0;
            return ((3.14159 * r) * r);
        }
        if (__match_value_0.tag == ShapeTag::Rectangle) {
            auto __data_0 = std::get<Shape_Rectangle>(__match_value_0.data);
            auto w = __data_0._0;
            auto h = __data_0._1;
            return (w * h);
        }
        if (__match_value_0.tag == ShapeTag::Point) {
            return 0.0;
        }
        throw std::runtime_error("non-exhaustive match");
    }();
}

int32_t main() {
    Shape circle = Shape::Circle(5.0);
    Shape rect = Shape::Rectangle(10.0, 20.0);
    ([&]{ std::cout << "Circle area: "; std::cout << area(circle); std::cout << std::endl; }());
    ([&]{ std::cout << "Rectangle area: "; std::cout << area(rect); std::cout << std::endl; }());
    return 0;
}

