// Generated by mana-compiler from c:/dev/mana-lang/tests/playground/variables.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"



int32_t main() {
    int32_t x = 42;
    std::string name = "Alice";
    int32_t counter = 0;
    counter = (counter + 1);
    double pi = 3.1415899999999999;
    bool flag = true;
    ([&]{ std::cout << "x = "; std::cout << x; std::cout << ", counter = "; std::cout << counter; std::cout << std::endl; }());
    ([&]{ std::cout << "Hello, "; std::cout << name; std::cout << "!"; std::cout << std::endl; }());
    return 0;
}

