// Generated by mana-compiler from C:/dev/mana-lang/examples/adt_test.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include "mana_runtime.h"


enum class Color {
    Red,
    Green,
    Blue
};

struct Message_Move {
    int32_t _0;
    int32_t _1;
};

struct Message_Write {
    std::string _0;
};

struct Message_ChangeColor {
    int32_t _0;
    int32_t _1;
    int32_t _2;
};

enum class MessageTag {
    Quit,
    Move,
    Write,
    ChangeColor
};

struct Message {
    MessageTag tag;
    std::variant<std::monostate, Message_Move, Message_Write, Message_ChangeColor> data;

    static Message Quit() {
        return Message{MessageTag::Quit, std::monostate{}};
    }
    static Message Move(int32_t v0, int32_t v1) {
        return Message{MessageTag::Move, Message_Move{v0, v1}};
    }
    static Message Write(std::string v0) {
        return Message{MessageTag::Write, Message_Write{v0}};
    }
    static Message ChangeColor(int32_t v0, int32_t v1, int32_t v2) {
        return Message{MessageTag::ChangeColor, Message_ChangeColor{v0, v1, v2}};
    }
};

struct Event_Click {
    int32_t x;
    int32_t y;
};

struct Event_KeyPress {
    std::string key;
    std::string modifier;
};

struct Event_Resize {
    int32_t width;
    int32_t height;
};

enum class EventTag {
    Click,
    KeyPress,
    Resize
};

struct Event {
    EventTag tag;
    std::variant<std::monostate, Event_Click, Event_KeyPress, Event_Resize> data;

    static Event Click(int32_t x, int32_t y) {
        return Event{EventTag::Click, Event_Click{x, y}};
    }
    static Event KeyPress(std::string key, std::string modifier) {
        return Event{EventTag::KeyPress, Event_KeyPress{key, modifier}};
    }
    static Event Resize(int32_t width, int32_t height) {
        return Event{EventTag::Resize, Event_Resize{width, height}};
    }
};

int32_t main() {
    mana::println("=== Algebraic Data Types Test ===");
    mana::println();
    mana::println("1. Simple enum:");
    Color color = Color::Red;
    mana::println("  Created Color::Red");
    mana::println();
    mana::println("2. Tuple variant enum (Message):");
    Message quit_msg = Message::Quit();
    mana::println("  Created Message::Quit");
    Message move_msg = Message::Move(10, 20);
    mana::println("  Created Message::Move(10, 20)");
    Message write_msg = Message::Write("Hello, ADT!");
    mana::println("  Created Message::Write(\"Hello, ADT!\")");
    Message color_msg = Message::ChangeColor(255, 128, 64);
    mana::println("  Created Message::ChangeColor(255, 128, 64)");
    mana::println();
    mana::println("3. Struct variant enum (Event):");
    Event click = Event::Click(100, 200);
    mana::println("  Created Event::Click { x: 100, y: 200 }");
    Event keypress = Event::KeyPress("Enter", "Ctrl");
    mana::println("  Created Event::KeyPress { key: \"Enter\", modifier: \"Ctrl\" }");
    Event resize = Event::Resize(800, 600);
    mana::println("  Created Event::Resize { width: 800, height: 600 }");
    mana::println();
    mana::println("=== All ADT tests passed! ===");
    return 0;
}

