// Generated by mana-compiler from C:/dev/mana-lang/examples/array_fill_test.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== Array Fill Syntax Test ===");
    mana::println();
    mana::Vec<int32_t> zeros = mana::Vec<decltype(0)>(5, 0);
    mana::print("zeros len: ");
    mana::println(zeros.len());
    mana::print("zeros[0]: ");
    mana::println(zeros[0]);
    mana::Vec<int32_t> ones = mana::Vec<decltype(1)>(3, 1);
    mana::print("ones len: ");
    mana::println(ones.len());
    mana::print("ones: ");
    for (int32_t i = 0; i < ones.len(); ++i)     {
        mana::print(ones[i]);
        mana::print(" ");
    }
    mana::println();
    mana::println();
    mana::println("=== Array fill tests passed! ===");
    return 0;
}

