// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    mana::assert_(((1 + 1) == 2));
    mana::println("passed: 1 + 1 == 2");
    mana::assert_eq(5, 5);
    mana::println("passed: assert_eq(5, 5)");
    mana::assert_ne(5, 10);
    mana::println("passed: assert_ne(5, 10)");
    mana::assert_eq("hello", "hello");
    mana::println("passed: assert_eq strings");
    mana::println("All assertions passed!");
    return 0;
}

