// Generated by mana-compiler from C:/dev/mana-lang/examples/assoc_types.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

struct IntBox {
    int32_t value;
};

struct StringBox {
    std::string text;
};

int32_t IntBox_size(IntBox& self) {
    return 1;
}

int32_t StringBox_size(StringBox& self) {
    return 1;
}

int32_t main() {
    mana::println("=== Associated Types Test ===");
    IntBox int_box = IntBox{.value = 42};
    StringBox str_box = StringBox{.text = "hello"};
    mana::print("IntBox size: ");
    mana::println(IntBox_size(int_box));
    mana::print("StringBox size: ");
    mana::println(StringBox_size(str_box));
    mana::println("=== All tests passed! ===");
    return 0;
}
