// Generated by mana-compiler from C:/dev/mana-lang/examples/binding_test.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    int32_t x = 5;
    std::string result = [&]() {
        auto __match_value_0 = x;
        if ([&]() { auto n = __match_value_0; return ((n > 10)); }()) { auto n = __match_value_0; return "large"; }
        if ([&]() { auto n = __match_value_0; return ((n > 0)); }()) { auto n = __match_value_0; return "positive"; }
        if ([&]() { auto n = __match_value_0; return ((n < 0)); }()) { auto n = __match_value_0; return "negative"; }
        return "zero";
    }();
    mana::println("x={}, result: {}", x, result);
    int32_t y = 7;
    int32_t doubled = [&]() {
        auto __match_value_1 = y;
        if ([&]() { auto n = __match_value_1; return ((n > 5)); }()) { auto n = __match_value_1; return (n * 2); }
        { auto n = __match_value_1; return n; }
    }();
    mana::println("y={}, doubled: {}", y, doubled);
    int32_t z = (-3);
    std::string sign = [&]() {
        auto __match_value_2 = z;
        if ([&]() { auto n = __match_value_2; return ((n > 0)); }()) { auto n = __match_value_2; return "positive"; }
        if ([&]() { auto n = __match_value_2; return ((n < 0)); }()) { auto n = __match_value_2; return "negative"; }
        return "zero";
    }();
    mana::println("z={}, sign: {}", z, sign);
    return 0;
}

