// Generated by mana-compiler from C:/dev/mana-lang/examples/cast_test.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== Type Casting Test ===");
    mana::println();
    int32_t a = 42;
    float b = static_cast<float>(a);
    mana::print("42 as f32 = ");
    mana::println(b);
    float c = 3.7;
    int32_t d = static_cast<int32_t>(c);
    mana::print("3.7 as i32 = ");
    mana::println(d);
    int32_t e = 100;
    int64_t f = static_cast<int64_t>(e);
    mana::print("100 as i64 = ");
    mana::println(f);
    int64_t g = 300;
    int8_t h = static_cast<int8_t>(g);
    mana::print("300 as i8 = ");
    mana::println(h);
    int8_t i = 'A';
    int32_t j = static_cast<int32_t>(i);
    mana::print("'A' as i32 = ");
    mana::println(j);
    mana::println();
    mana::println("=== Type casting tests passed! ===");
    return 0;
}

