// Generated by mana-compiler from C:/dev/mana-lang/examples/char_test.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== Character Literal Test ===");
    mana::println();
    int8_t a = 'A';
    int8_t b = 'B';
    int8_t space = ' ';
    mana::print("Character 'A' as i8: ");
    mana::println(a);
    mana::print("Character 'B' as i8: ");
    mana::println(b);
    mana::print("Character ' ' as i8: ");
    mana::println(space);
    mana::println();
    int8_t newline = '\n';
    int8_t tab = '\t';
    int8_t backslash = '\\';
    int8_t single_quote = '\'';
    mana::print("Newline as i8: ");
    mana::println(newline);
    mana::print("Tab as i8: ");
    mana::println(tab);
    mana::print("Backslash as i8: ");
    mana::println(backslash);
    mana::print("Single quote as i8: ");
    mana::println(single_quote);
    mana::println();
    int8_t zero = '0';
    int8_t nine = '9';
    mana::print("'0' as i8: ");
    mana::println(zero);
    mana::print("'9' as i8: ");
    mana::println(nine);
    mana::println();
    mana::println("=== Character literal tests passed! ===");
    return 0;
}

