// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    auto double_fn = [&](int32_t x) { return (x * 2); };
    int32_t multiplier = 3;
    auto triple = [&](int32_t x) { return (x * multiplier); };
    int32_t result1 = double_fn(5);
    int32_t result2 = triple(4);
    mana::println(result1);
    mana::println(result2);
    auto compute = [&](int32_t x) -> int32_t {
        int32_t y = (x + 1);
        return (y * 2);
    };
    int32_t result3 = compute(5);
    mana::println(result3);
    return (result1 + result2);
}

