// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== Compound Assignment Test ===");
    mana::println();
    int32_t a = 10;
    a = (a + 5);
    mana::print("10 += 5 = ");
    mana::println(a);
    int32_t b = 20;
    b = (b - 8);
    mana::print("20 -= 8 = ");
    mana::println(b);
    int32_t c = 4;
    c = (c * 3);
    mana::print("4 *= 3 = ");
    mana::println(c);
    int32_t d = 15;
    d = (d / 3);
    mana::print("15 /= 3 = ");
    mana::println(d);
    int32_t e = 17;
    e = (e % 5);
    mana::print("17 %= 5 = ");
    mana::println(e);
    double f = 2.0;
    f = std::pow(f, 4.0);
    mana::print("2 **= 4 = ");
    mana::println(f);
    int32_t g = 15;
    g = (g & 10);
    mana::print("0b1111 &= 0b1010 = ");
    mana::println(g);
    int32_t h = 10;
    h = (h | 5);
    mana::print("0b1010 |= 0b0101 = ");
    mana::println(h);
    int32_t i = 15;
    i = (i ^ 10);
    mana::print("0b1111 ^= 0b1010 = ");
    mana::println(i);
    int32_t j = 1;
    j = (j << 4);
    mana::print("1 <<= 4 = ");
    mana::println(j);
    int32_t k = 32;
    k = (k >> 2);
    mana::print("32 >>= 2 = ");
    mana::println(k);
    mana::println();
    mana::println("=== Compound assignment tests passed! ===");
    return 0;
}

