// Generated by mana-compiler from C:/dev/mana-lang/examples/compound.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include "mana_runtime.h"

int32_t main() {
    int32_t x = 10;
    x = (x + 5);
    mana::println(x);
    x = (x - 3);
    mana::println(x);
    x = (x * 2);
    mana::println(x);
    x = (x / 4);
    mana::println(x);
    return 0;
}

