// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    const float PI = 3.14159;
    ([&]{ std::cout << "PI = "; std::cout << PI; std::cout << std::endl; }());
    const int32_t MAX_SIZE = 100;
    ([&]{ std::cout << "MAX_SIZE = "; std::cout << MAX_SIZE; std::cout << std::endl; }());
    const std::string GREETING = "Hello, World!";
    mana::println(GREETING);
    return 0;
}

