// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t greet(std::string name, std::string greeting = "Hello") {
    mana::print(greeting);
    mana::print(", ");
    mana::print(name);
    mana::println("!");
    return 0;
}

int32_t add(int32_t a, int32_t b = 10, int32_t c = 5) {
    return ((a + b) + c);
}

int32_t main() {
    mana::println("=== Default Parameters Test ===");
    mana::println();
    greet("World");
    greet("Mana", "Welcome");
    mana::println();
    mana::print("add(1): ");
    mana::println(add(1));
    mana::print("add(1, 20): ");
    mana::println(add(1, 20));
    mana::print("add(1, 20, 30): ");
    mana::println(add(1, 20, 30));
    mana::println();
    mana::println("Done!");
    return 0;
}

