// Generated by mana-compiler from destructure.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include "mana_runtime.h"

struct Point {
    int32_t x;
    int32_t y;
};

void test_point() {
    Point p = Point{.x = 10, .y = 20};
    auto __ds_0 = p;
    auto x = __ds_0.x;
    auto y = __ds_0.y;
    mana::println(x);
    mana::println(y);
}

void test_array() {
    std::array<int32_t, 3> arr = {100, 200, 300};
    auto __ds_1 = arr;
    auto a = __ds_1[0];
    auto b = __ds_1[1];
    auto c = __ds_1[2];
    mana::println(a);
    mana::println(b);
    mana::println(c);
}

int32_t main() {
    test_point();
    test_array();
    return 0;
}

