// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

std::tuple<int32_t, int32_t> get_point() {
    return std::make_tuple(10, 20);
}

int32_t main() {
    auto __ds_0 = get_point();
    auto x = std::get<0>(__ds_0);
    auto y = std::get<1>(__ds_0);
    ([&]{ std::cout << "x="; std::cout << x; std::cout << ", y="; std::cout << y; std::cout << std::endl; }());
    auto __ds_1 = std::make_tuple(1, 2, 3);
    auto a = std::get<0>(__ds_1);
    auto b = std::get<1>(__ds_1);
    auto c = std::get<2>(__ds_1);
    ([&]{ std::cout << "a="; std::cout << a; std::cout << ", b="; std::cout << b; std::cout << ", c="; std::cout << c; std::cout << std::endl; }());
    int32_t m = 5;
    int32_t n = 10;
    auto __ds_2 = std::make_tuple(n, m);
    auto tmp_m = std::get<0>(__ds_2);
    auto tmp_n = std::get<1>(__ds_2);
    m = tmp_m;
    n = tmp_n;
    ([&]{ std::cout << "swapped: m="; std::cout << m; std::cout << ", n="; std::cout << n; std::cout << std::endl; }());
    return 0;
}

