// Generated by mana-compiler from dynamic_dispatch.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include "mana_runtime.h"

// Trait: Drawable
struct Drawable {
    virtual ~Drawable() = default;
    virtual void draw() = 0;
    virtual float area() = 0;
};

struct Circle {
    float radius;
};

struct Rectangle {
    float width;
    float height;
};

void Circle_draw(Circle& self) {
    mana::println("Drawing a circle");
}

float Circle_area(Circle& self) {
    return ((self.radius * self.radius) * 3.14159);
}

// Dynamic dispatch wrapper: Circle as Drawable
struct Circle_as_Drawable : public Drawable {
    Circle& inner;
    explicit Circle_as_Drawable(Circle& obj) : inner(obj) {}
    void draw() override {
        Circle_draw(inner);
    }
    float area() override {
        return Circle_area(inner);
    }
};

inline Drawable* as_Drawable(Circle& obj) {
    static Circle_as_Drawable wrapper(obj);
    return &wrapper;
}

void Rectangle_draw(Rectangle& self) {
    mana::println("Drawing a rectangle");
}

float Rectangle_area(Rectangle& self) {
    return (self.width * self.height);
}

// Dynamic dispatch wrapper: Rectangle as Drawable
struct Rectangle_as_Drawable : public Drawable {
    Rectangle& inner;
    explicit Rectangle_as_Drawable(Rectangle& obj) : inner(obj) {}
    void draw() override {
        Rectangle_draw(inner);
    }
    float area() override {
        return Rectangle_area(inner);
    }
};

inline Drawable* as_Drawable(Rectangle& obj) {
    static Rectangle_as_Drawable wrapper(obj);
    return &wrapper;
}

void draw_shape(Drawable* shape) {
    shape->draw();
}

int32_t main() {
    Circle c = Circle{.radius = 5.0};
    Rectangle r = Rectangle{.width = 3.0, .height = 4.0};
    mana::println("Static dispatch:");
    Circle_draw(c);
    Rectangle_draw(r);
    mana::println(Circle_area(c));
    mana::println(Rectangle_area(r));
    return 0;
}

