// Generated by mana-compiler from error_handling.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include "mana_runtime.h"

mana::Result<int32_t, std::string> safe_divide(int32_t a, int32_t b) {
    if ((b == 0))     {
        return mana::Err("division by zero");
    }
    return mana::Ok((a / b));
}

mana::Result<int32_t, std::string> calculate(int32_t x, int32_t y) {
    int32_t result = [&]() {
        auto __try_0 = safe_divide(x, y);
        if (__try_0.__is_err()) {
            throw std::runtime_error("error propagation");
        }
        return __try_0.__unwrap_ok();
    }();
    return mana::Ok((result * 2));
}

mana::Option<int32_t> test_option() {
    return mana::Some(42);
}

int32_t use_option() {
    mana::Option<int32_t> opt = test_option();
    if (opt.is_some())     {
        return opt.unwrap();
    }
    return 0;
}

int32_t main() {
    mana::Result<int32_t, std::string> r1 = safe_divide(10, 2);
    if (r1.is_ok())     {
        mana::println(r1.unwrap());
    }
    mana::Result<int32_t, std::string> r2 = safe_divide(10, 0);
    if (r2.is_err())     {
        mana::println("Got expected error");
    }
    int32_t val = use_option();
    mana::println(val);
    mana::Option<int32_t> some_val = mana::Some(100);
    mana::println(some_val.unwrap());
    return 0;
}

