// Generated by mana-compiler from C:/dev/mana-lang/examples/exclusive_range_test.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include "mana_runtime.h"


std::string categorize_exclusive(int32_t n) {
    return [&]() {
        auto __match_value_0 = n;
        if ((__match_value_0 >= 0 && __match_value_0 < 10)) return "0-9";
        if ((__match_value_0 >= 10 && __match_value_0 < 20)) return "10-19";
        if ((__match_value_0 >= 20 && __match_value_0 < 50)) return "20-49";
        return "50+";
    }();
}

std::string categorize_inclusive(int32_t n) {
    return [&]() {
        auto __match_value_1 = n;
        if ((__match_value_1 >= 0 && __match_value_1 <= 9)) return "0-9";
        if ((__match_value_1 >= 10 && __match_value_1 <= 19)) return "10-19";
        if ((__match_value_1 >= 20 && __match_value_1 <= 49)) return "20-49";
        return "50+";
    }();
}

std::string http_status(int32_t code) {
    return [&]() {
        auto __match_value_2 = code;
        if ((__match_value_2 >= 100 && __match_value_2 < 200)) return "Informational";
        if ((__match_value_2 >= 200 && __match_value_2 < 300)) return "Success";
        if ((__match_value_2 >= 300 && __match_value_2 < 400)) return "Redirect";
        if ((__match_value_2 >= 400 && __match_value_2 < 500)) return "Client Error";
        if ((__match_value_2 >= 500 && __match_value_2 < 600)) return "Server Error";
        return "Unknown";
    }();
}

int32_t main() {
    mana::println("=== Exclusive Range Patterns Test ===");
    mana::println();
    mana::println("1. Exclusive range patterns (..):");
    mana::println((std::string("  0 is in range ") + mana::to_string(categorize_exclusive(0))));
    mana::println((std::string("  9 is in range ") + mana::to_string(categorize_exclusive(9))));
    mana::println((std::string("  10 is in range ") + mana::to_string(categorize_exclusive(10))));
    mana::println((std::string("  19 is in range ") + mana::to_string(categorize_exclusive(19))));
    mana::println((std::string("  20 is in range ") + mana::to_string(categorize_exclusive(20))));
    mana::println((std::string("  49 is in range ") + mana::to_string(categorize_exclusive(49))));
    mana::println((std::string("  50 is in range ") + mana::to_string(categorize_exclusive(50))));
    mana::println();
    mana::println("2. Boundary comparison (exclusive vs inclusive):");
    mana::println((std::string("  9 exclusive: ") + mana::to_string(categorize_exclusive(9))));
    mana::println((std::string("  9 inclusive: ") + mana::to_string(categorize_inclusive(9))));
    mana::println((std::string("  10 exclusive: ") + mana::to_string(categorize_exclusive(10))));
    mana::println((std::string("  10 inclusive: ") + mana::to_string(categorize_inclusive(10))));
    mana::println();
    mana::println("3. HTTP status code classification:");
    mana::println((std::string("  100: ") + mana::to_string(http_status(100))));
    mana::println((std::string("  200: ") + mana::to_string(http_status(200))));
    mana::println((std::string("  301: ") + mana::to_string(http_status(301))));
    mana::println((std::string("  404: ") + mana::to_string(http_status(404))));
    mana::println((std::string("  500: ") + mana::to_string(http_status(500))));
    mana::println((std::string("  999: ") + mana::to_string(http_status(999))));
    mana::println();
    mana::println("=== All exclusive range tests passed! ===");
    return 0;
}

