// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== File I/O Test ===");
    mana::println();
    std::string test_file = "test_output.txt";
    mana::println("Writing to file...");
    auto write_result = mana::write_file(test_file, "Hello, File!\nThis is line 2.\nLine 3 here.");
    if (write_result.is_err()) {
        mana::println("Write failed!");
        return 1;
    }
    mana::println("Write successful!");
    mana::print("File exists: ");
    mana::println(mana::file_exists(test_file));
    mana::println();
    mana::println("Reading entire file:");
    auto read_result = mana::read_file(test_file);
    if (read_result.is_ok()) {
        mana::println(read_result.unwrap());
    }
    mana::println();
    mana::println("Reading lines:");
    auto lines_result = mana::read_lines(test_file);
    if (lines_result.is_ok()) {
        auto lines = lines_result.unwrap();
        for (int32_t i = 0; i < lines.len(); ++i) {
            mana::print("  Line ");
            mana::print(i);
            mana::print(": ");
            mana::println(lines.at(i));
        }
    }
    mana::println();
    mana::println("Appending to file...");
    auto append_result = mana::append_file(test_file, "\nAppended line!");
    if (append_result.is_ok()) {
        mana::println("Append successful!");
    }
    auto read_result2 = mana::read_file(test_file);
    if (read_result2.is_ok()) {
        mana::println("After append:");
        mana::println(read_result2.unwrap());
    }
    mana::println();
    mana::println("Deleting file...");
    auto delete_result = mana::delete_file(test_file);
    if (delete_result.is_ok()) {
        mana::println("Delete successful!");
    }
    mana::print("File exists after delete: ");
    mana::println(mana::file_exists(test_file));
    mana::println();
    mana::println("Done!");
    return 0;
}

