// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== Float Modulus Test ===");
    mana::println();
    int32_t a = mana::mod(17, 5);
    mana::print("17 % 5 = ");
    mana::println(a);
    double b = mana::mod(7.5, 2.5);
    mana::print("7.5 % 2.5 = ");
    mana::println(b);
    double c = mana::mod(10.0, 3.0);
    mana::print("10.0 % 3.0 = ");
    mana::println(c);
    double d = mana::mod(5.5, 1.1);
    mana::print("5.5 % 1.1 = ");
    mana::println(d);
    double e = mana::mod((-7.5), 2.5);
    mana::print("-7.5 % 2.5 = ");
    mana::println(e);
    mana::println();
    mana::println("=== Float modulus tests passed! ===");
    return 0;
}

