// Generated by mana-compiler from C:/dev/mana-lang/examples/forin.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include "mana_runtime.h"

void test_basic_range() {
    mana::println("Exclusive range 0..5:");
    for (int32_t i = 0; i < 5; ++i)     {
        mana::print(i);
        mana::print(" ");
    }
    mana::println();
}

void test_inclusive_range() {
    mana::println("Inclusive range 1..=5:");
    for (int32_t i = 1; i <= 5; ++i)     {
        mana::print(i);
        mana::print(" ");
    }
    mana::println();
}

void test_sum() {
    int32_t sum = 0;
    for (int32_t i = 1; i <= 10; ++i)     {
        sum = (sum + i);
    }
    mana::print("Sum of 1 to 10: ");
    mana::println(sum);
}

void test_array_iteration() {
    std::array<int32_t, 5> arr = {10, 20, 30, 40, 50};
    mana::println("Array elements:");
    for (auto val : arr)     {
        mana::print(val);
        mana::print(" ");
    }
    mana::println();
}

int32_t main() {
    test_basic_range();
    test_inclusive_range();
    test_sum();
    test_array_iteration();
    return 0;
}

