// Generated by mana-compiler from C:/dev/mana-lang/examples/format_test.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== F-String Format Specifiers Test ===");
    mana::println();
    mana::println("1. Float precision:");
    float pi = 3.14159265359;
    mana::println((std::string("  pi = ") + mana::to_string(pi)));
    mana::println((std::string("  pi with 2 decimals = ") + mana::format(pi, ".2f")));
    mana::println((std::string("  pi with 4 decimals = ") + mana::format(pi, ".4f")));
    mana::println((std::string("  pi with 0 decimals = ") + mana::format(pi, ".0f")));
    mana::println();
    mana::println("2. Integer padding:");
    int32_t num = 42;
    mana::println((std::string("  num = ") + mana::to_string(num)));
    mana::println((std::string("  num with 5 width = ") + mana::format(num, "5d")));
    mana::println((std::string("  num zero-padded to 5 = ") + mana::format(num, "05d")));
    int32_t small = 7;
    mana::println((std::string("  small zero-padded to 3 = ") + mana::format(small, "03d")));
    mana::println();
    mana::println("3. Hexadecimal:");
    int32_t hex_val = 255;
    mana::println((std::string("  255 in hex lowercase = ") + mana::format(hex_val, "x")));
    mana::println((std::string("  255 in hex uppercase = ") + mana::format(hex_val, "X")));
    mana::println((std::string("  255 in hex, 4 digits = ") + mana::format(hex_val, "04x")));
    int32_t color = 16711680;
    mana::println((std::string("  red color in hex = ") + mana::format(color, "06X")));
    mana::println();
    mana::println("4. Binary:");
    int32_t bits = 42;
    mana::println((std::string("  42 in binary = ") + mana::format(bits, "b")));
    mana::println((std::string("  42 in binary, 8 bits = ") + mana::format(bits, "08b")));
    mana::println();
    mana::println("5. Octal:");
    int32_t oct_val = 64;
    mana::println((std::string("  64 in octal = ") + mana::format(oct_val, "o")));
    mana::println();
    mana::println("6. String padding:");
    std::string name = "Alice";
    mana::println((std::string("  [") + mana::format(name, "10") + std::string("] (right-padded to 10)")));
    mana::println((std::string("  [") + mana::format(name, "-10") + std::string("] (left-padded to 10)")));
    mana::println();
    mana::println("7. Mixed formatting:");
    int32_t x = 5;
    float y = 3.14159;
    mana::println((std::string("  x=") + mana::format(x, "03d") + std::string(", y=") + mana::format(y, ".2f")));
    mana::println();
    mana::println("8. Expressions with format specifiers:");
    int32_t a = 10;
    int32_t b = 20;
    mana::println((std::string("  ") + mana::to_string(a) + std::string(" + ") + mana::to_string(b) + std::string(" = ") + mana::format((a + b), "04d")));
    float price = 19.99;
    float tax = 0.08;
    mana::println((std::string("  Total: $") + mana::format((price * (1.0 + tax)), ".2f")));
    mana::println();
    mana::println("=== All format specifier tests passed! ===");
    return 0;
}

