// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include "mana_runtime.h"


enum class Color {
    Red,
    Green,
    Blue
};

std::string Color_name(Color& self) {
    return [&]() {
        auto __match_value_0 = self;
        if (__match_value_0 == Color::Red) return "red";
        if (__match_value_0 == Color::Green) return "green";
        if (__match_value_0 == Color::Blue) return "blue";
        throw std::runtime_error("non-exhaustive match");
    }();
}

int32_t main() {
    Color c = Color::Red;
    std::string msg = (std::string("The color is ") + mana::to_string(Color_name(c)));
    mana::println(msg);
    return 0;
}

