// Generated by mana-compiler from C:/dev/mana-lang/examples/fstrings.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== F-String Demo ===");
    mana::println();
    mana::println("1. Basic interpolation:");
    std::string name = "Alice";
    std::string greeting = (std::string("Hello, ") + mana::to_string(name) + std::string("!"));
    mana::println(greeting);
    mana::println();
    mana::println("2. Number interpolation:");
    int32_t age = 30;
    std::string message = (mana::to_string(name) + std::string(" is ") + mana::to_string(age) + std::string(" years old."));
    mana::println(message);
    mana::println();
    mana::println("3. Expression interpolation:");
    int32_t x = 5;
    int32_t y = 3;
    std::string result = (mana::to_string(x) + std::string(" + ") + mana::to_string(y) + std::string(" = ") + mana::to_string((x + y)));
    mana::println(result);
    mana::println();
    mana::println("4. Multiple variables:");
    std::string first = "Hello";
    std::string second = "World";
    std::string combined = (mana::to_string(first) + std::string(", ") + mana::to_string(second) + std::string("!"));
    mana::println(combined);
    mana::println();
    mana::println("5. Boolean interpolation:");
    bool flag = true;
    std::string status = (std::string("Flag is ") + mana::to_string(flag));
    mana::println(status);
    mana::println();
    mana::println("6. Direct f-string in println:");
    int32_t count = 42;
    mana::println((std::string("The answer is ") + mana::to_string(count)));
    mana::println();
    mana::println("=== All f-string tests passed! ===");
    return 0;
}

