// Generated by mana-compiler from C:/dev/mana-lang/examples/generics.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include "mana_runtime.h"

template<typename T>
struct Box {
    T value;
};

template<typename T>
T identity(T x) {
    return x;
}

int32_t main() {
    int32_t x = identity(42);
    mana::println(x);
    Box<int32_t> b = Box<int32_t>{.value = 100};
    mana::println(b.value);
    return 0;
}

