// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    int32_t x = 5;
    std::string result = [&]() {
        auto __match_value_0 = x;
        if ((__match_value_0 == 1 || __match_value_0 == 2 || __match_value_0 == 3) && ((x < 5))) return "small";
        if ((__match_value_0 == 4 || __match_value_0 == 5 || __match_value_0 == 6) && ((x > 4))) return "medium";
        return "other";
    }();
    mana::println(result);
    int32_t y = 15;
    std::string result2 = [&]() {
        auto __match_value_1 = y;
        if ((__match_value_1 == 10) && ((y > 12))) return "ten but y > 12";
        if ((__match_value_1 == 10)) return "just ten";
        if (((y > 10))) return "greater than 10";
        return "small";
    }();
    mana::println(result2);
    return 0;
}

