// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    mana::HashMap<std::string, int32_t> scores = {};
    scores.insert("Alice", 95);
    scores.insert("Bob", 87);
    scores.insert("Charlie", 92);
    scores.insert("Diana", 88);
    mana::println("Testing get:");
    mana::Option<int32_t> alice_score = scores.get("Alice");
    if (alice_score.is_some())     {
        ([&]{ std::cout << "Alice: "; std::cout << alice_score.unwrap(); std::cout << std::endl; }());
    }
    mana::Option<int32_t> eve_score = scores.get("Eve");
    if (eve_score.is_none())     {
        mana::println("Eve not found");
    }
    mana::println("Testing contains:");
    bool has_bob = scores.contains("Bob");
    if (has_bob)     {
        mana::println("Bob exists");
    }
    bool has_frank = scores.contains("Frank");
    if ((!has_frank))     {
        mana::println("Frank doesn't exist");
    }
    ([&]{ std::cout << "Size: "; std::cout << scores.len(); std::cout << std::endl; }());
    mana::println("Testing remove:");
    bool removed = scores.remove("Charlie");
    if (removed)     {
        mana::println("Charlie removed");
    }
    ([&]{ std::cout << "Size after remove: "; std::cout << scores.len(); std::cout << std::endl; }());
    mana::println("All keys:");
    mana::Vec<std::string> all_keys = scores.keys();
    for (int32_t i = 0; i < all_keys.len(); ++i)     {
        ([&]{ std::cout << "  "; std::cout << all_keys.at(i); std::cout << std::endl; }());
    }
    return 0;
}

