// Generated by mana-compiler from C:/dev/mana-lang/examples/hello.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include "mana_runtime.h"


int32_t main() {
    int32_t x = 10;
    int32_t y = 20;
    int32_t sum = (x + y);
    mana::print("Sum: ");
    mana::println(sum);
    return 0;
}

