// Generated by mana-compiler from C:/dev/mana-lang/examples/hex_binary_test.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== Binary and Hex Literal Test ===");
    mana::println();
    int32_t b1 = 10;
    int32_t b2 = 240;
    int32_t b3 = 255;
    mana::print("0b1010 = ");
    mana::println(b1);
    mana::print("0b1111_0000 = ");
    mana::println(b2);
    mana::print("0B11111111 = ");
    mana::println(b3);
    mana::println();
    int32_t h1 = 255;
    int32_t h2 = 6699;
    int32_t h3 = 3735928559;
    mana::print("0xFF = ");
    mana::println(h1);
    mana::print("0x1A2B = ");
    mana::println(h2);
    mana::print("0xDEAD_BEEF = ");
    mana::println(h3);
    mana::println();
    mana::println("=== Binary and hex tests passed! ===");
    return 0;
}

