// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== If Expression Test ===");
    mana::println();
    int32_t x = 5;
    int32_t y = ((x > 3) ? 10 : 20);
    mana::print("x=5, if x > 3 { 10 } else { 20 } = ");
    mana::println(y);
    int32_t a = 7;
    int32_t b = ((a > 10) ? 100 : ((a > 5) ? 50 : 10));
    mana::print("a=7, nested if = ");
    mana::println(b);
    int32_t max = ((x > a) ? x : a);
    mana::print("max(5, 7) = ");
    mana::println(max);
    bool flag = true;
    int32_t val = (flag ? 1 : 0);
    mana::print("if true { 1 } else { 0 } = ");
    mana::println(val);
    mana::println();
    mana::println("=== If expression tests passed! ===");
    return 0;
}

