// Generated by mana-compiler from C:/dev/mana-lang/examples/iflet.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include "mana_runtime.h"

mana::Option<int32_t> get_value(bool return_some) {
    if (return_some)     {
        return mana::Some(42);
    }
    mana::Option<int32_t> empty = mana::Some(0);
    return mana::Some(0);
}

mana::Result<int32_t, std::string> divide(int32_t a, int32_t b) {
    if ((b == 0))     {
        return mana::Err("division by zero");
    }
    return mana::Ok((a / b));
}

int32_t main() {
    mana::println("=== if-let Demo ===");
    mana::println();
    mana::println("1. if let Some (value present):");
    mana::Option<int32_t> opt = mana::Some(42);
    if (opt.is_some()) {
        auto value = opt.unwrap();
        mana::print("Got value: ");
        mana::println(value);
    } else     {
        mana::println("Got None");
    }

    mana::println();
    mana::println("2. if let Ok:");
    mana::Result<int32_t, std::string> result = divide(10, 2);
    if (result.is_ok()) {
        auto value = result.unwrap();
        mana::print("Result: ");
        mana::println(value);
    } else     {
        mana::println("Got error");
    }

    mana::println();
    mana::println("3. if let Err:");
    mana::Result<int32_t, std::string> result2 = divide(10, 0);
    if (result2.is_err()) {
        auto msg = result2.unwrap_err();
        mana::print("Error: ");
        mana::println(msg);
    } else     {
        mana::println("Got Ok");
    }

    mana::println();
    mana::println("4. Chained if-let:");
    mana::Result<int32_t, std::string> ok_result = mana::Ok(100);
    if (ok_result.is_ok()) {
        auto v = ok_result.unwrap();
        mana::print("Ok value: ");
        mana::println(v);
    } else     {
        mana::println("Was an error");
    }

    mana::println();
    mana::println("=== All if-let tests passed! ===");
    return 0;
}

