// Generated by mana-compiler from examples/impl_minimal.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"


struct Counter {
    int32_t value;
};

int32_t Counter_get(Counter& self) {
    return 42;
}

int main() {
    return 0;
}

