// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include "mana_runtime.h"


enum class Color {
    Red,
    Green,
    Blue
};

bool Color_is_red(Color& self) {
    return [&]() {
        auto __match_value_0 = self;
        if (__match_value_0 == Color::Red) return true;
        return false;
    }();
}

int32_t check_color(Color c) {
    bool result = Color_is_red(c);
    if (result) {
        return 1;
    }
    return 0;
}

int32_t main() {
    Color c = Color::Red;
    int32_t r = check_color(c);
    mana::println("Done");
    return r;
}

