// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"


template<typename T>
T identity(T x) {
    return x;
}

int32_t add_one(int32_t x) {
    return (x + 1);
}

int32_t main() {
    int32_t a = identity(42);
    std::string b = identity("hello");
    bool c = identity(true);
    auto square = [&](int32_t x) { return (x * x); };
    auto result = square(5);
    mana::println(result);
    int32_t multiplier = 10;
    auto times_ten = [&](int32_t n) { return (n * multiplier); };
    mana::println(times_ten(7));
    auto make_adder = [&](int32_t x) { return [&](int32_t y) { return (x + y); }; };
    mana::println(a);
    mana::println(b);
    mana::println(c);
    return 0;
}

