// Generated by mana-compiler from C:/dev/mana-lang/examples/inference.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include "mana_runtime.h"

struct Point {
    int32_t x;
    int32_t y;
};

int32_t main() {
    int32_t x = 42;
    mana::print("Integer: ");
    mana::println(x);
    float f = 3.14;
    mana::print("Float: ");
    mana::println(f);
    std::string s = "Hello, Mana!";
    mana::print("String: ");
    mana::println(s);
    bool b = true;
    mana::print("Boolean: ");
    mana::println(b);
    int32_t sum = (10 + 20);
    mana::print("10 + 20 = ");
    mana::println(sum);
    bool cmp = (5 < 10);
    mana::print("5 < 10 = ");
    mana::println(cmp);
    mana::println();
    mana::println("All type inference tests passed!");
    return 0;
}

