// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== Destructuring For-In Test ===");
    mana::println();
    mana::println("HashMap iteration with destructuring:");
    mana::HashMap<std::string, int32_t> scores = {};
    scores.insert("Alice", 95);
    scores.insert("Bob", 87);
    scores.insert("Charlie", 92);
    for (auto& [name, score] : scores) {
        mana::print(name);
        mana::print(": ");
        mana::println(score);
    }
    mana::println();
    mana::println("Done!");
    return 0;
}
