// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include "mana_runtime.h"


int32_t main() {
    mana::println("=== Iterator Methods Test ===");
    mana::println();
    mana::Vec<int32_t> numbers = {1, 2, 3, 4, 5};
    mana::println("Original: 1, 2, 3, 4, 5");
    mana::print("Squared (map): ");
    auto squared = numbers.map([&](int32_t x) { return (x * x); });
    for (int32_t i = 0; i < squared.len(); ++i) {
        mana::print(squared.at(i));
        mana::print(" ");
    }
    mana::println();
    mana::print("Even only (filter): ");
    auto evens = numbers.filter([&](int32_t x) { return ((x % 2) == 0); });
    for (int32_t i = 0; i < evens.len(); ++i) {
        mana::print(evens.at(i));
        mana::print(" ");
    }
    mana::println();
    auto sum = numbers.fold(0, [&](int32_t acc, int32_t x) { return (acc + x); });
    mana::print("Sum (fold): ");
    mana::println(sum);
    auto has_even = numbers.any([&](int32_t x) { return ((x % 2) == 0); });
    mana::print("Has even? (any): ");
    mana::println(has_even);
    auto all_positive = numbers.all([&](int32_t x) { return (x > 0); });
    mana::print("All positive? (all): ");
    mana::println(all_positive);
    auto no_negatives = numbers.none([&](int32_t x) { return (x < 0); });
    mana::print("No negatives? (none): ");
    mana::println(no_negatives);
    auto even_count = numbers.count([&](int32_t x) { return ((x % 2) == 0); });
    mana::print("Count of evens: ");
    mana::println(even_count);
    auto found = numbers.find([&](int32_t x) { return (x > 3); });
    if (found.is_some()) {
        mana::print("First > 3 (find): ");
        mana::println(found.unwrap());
    }
    auto idx = numbers.find_index([&](int32_t x) { return (x == 3); });
    if (idx.is_some()) {
        mana::print("Index of 3 (find_index): ");
        mana::println(idx.unwrap());
    }
    mana::print("Take 3: ");
    auto first3 = numbers.take(3);
    for (int32_t i = 0; i < first3.len(); ++i) {
        mana::print(first3.at(i));
        mana::print(" ");
    }
    mana::println();
    mana::print("Skip 2: ");
    auto after2 = numbers.skip(2);
    for (int32_t i = 0; i < after2.len(); ++i) {
        mana::print(after2.at(i));
        mana::print(" ");
    }
    mana::println();
    auto first_elem = numbers.first();
    if (first_elem.is_some()) {
        mana::print("First: ");
        mana::println(first_elem.unwrap());
    }
    auto last_elem = numbers.last();
    if (last_elem.is_some()) {
        mana::print("Last: ");
        mana::println(last_elem.unwrap());
    }
    mana::print("Reversed (rev): ");
    auto reversed = numbers.rev();
    for (int32_t i = 0; i < reversed.len(); ++i) {
        mana::print(reversed.at(i));
        mana::print(" ");
    }
    mana::println();
    mana::print("Contains 3? ");
    mana::println(numbers.contains(3));
    mana::print("Contains 10? ");
    mana::println(numbers.contains(10));
    mana::Vec<int32_t> more = {6, 7, 8};
    auto combined = numbers.concat(more);
    mana::print("Concat with [6,7,8]: ");
    for (int32_t i = 0; i < combined.len(); ++i) {
        mana::print(combined.at(i));
        mana::print(" ");
    }
    mana::println();
    mana::print("Slice(1,4): ");
    auto middle = numbers.slice(1, 4);
    for (int32_t i = 0; i < middle.len(); ++i) {
        mana::print(middle.at(i));
        mana::print(" ");
    }
    mana::println();
    mana::print("Sum: ");
    mana::println(numbers.sum());
    mana::print("Product: ");
    mana::println(numbers.product());
    auto min = numbers.min_val();
    if (min.is_some()) {
        mana::print("Min: ");
        mana::println(min.unwrap());
    }
    auto max = numbers.max_val();
    if (max.is_some()) {
        mana::print("Max: ");
        mana::println(max.unwrap());
    }
    mana::Vec<int32_t> unsorted = {3, 1, 4, 1, 5, 9, 2, 6};
    mana::print("Unsorted: ");
    for (int32_t i = 0; i < unsorted.len(); ++i) {
        mana::print(unsorted.at(i));
        mana::print(" ");
    }
    mana::println();
    mana::print("Sorted: ");
    auto sorted = unsorted.sorted();
    for (int32_t i = 0; i < sorted.len(); ++i) {
        mana::print(sorted.at(i));
        mana::print(" ");
    }
    mana::println();
    mana::print("Dedup (sorted): ");
    auto deduped = sorted.dedup();
    for (int32_t i = 0; i < deduped.len(); ++i) {
        mana::print(deduped.at(i));
        mana::print(" ");
    }
    mana::println();
    mana::println();
    mana::println("Chained: filter(even).map(square).sum()");
    auto result = numbers.filter([&](int32_t x) { return ((x % 2) == 0); }).map([&](int32_t x) { return (x * x); }).sum();
    mana::print("Result: ");
    mana::println(result);
    mana::println();
    mana::println("All iterator methods tested successfully!");
    return 0;
}

