// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    mana::println("Vec iteration:");
    mana::Vec<int32_t> numbers = {10, 20, 30, 40, 50};
    for (auto n : numbers)     {
        ([&]{ std::cout << n; std::cout << std::endl; }());
    }
    mana::println("\nHashMap iteration:");
    mana::HashMap<std::string, int32_t> scores = {};
    scores.insert("Alice", 95);
    scores.insert("Bob", 87);
    scores.insert("Charlie", 92);
    for (auto pair : scores)     {
        mana::println("Entry");
    }
    return 0;
}

