// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== Loop Test ===");
    mana::println();
    int32_t count = 0;
    while (true)     {
        count = (count + 1);
        mana::print("Count: ");
        mana::println(count);
        if ((count >= 5))         {
            break;
        }
    }
    mana::println();
    mana::println("Loop with early break:");
    int32_t i = 0;
    while (true)     {
        i = (i + 1);
        if ((i == 3))         {
            mana::println("Skipping 3 with continue");
            continue;
        }
        mana::print("i = ");
        mana::println(i);
        if ((i >= 5))         {
            break;
        }
    }
    mana::println();
    mana::println("=== Loop tests passed! ===");
    return 0;
}

