// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include "mana_runtime.h"

mana::Option<int32_t> get_some() {
    return mana::Some(42);
}

mana::Option<int32_t> get_none() {
    return mana::None;
}

mana::Result<int32_t, std::string> get_ok() {
    return mana::Ok(100);
}

mana::Result<int32_t, std::string> get_err() {
    return mana::Err("something went wrong");
}

int32_t main() {
    mana::println("=== Option/Result Match Patterns Test ===");
    mana::println();
    mana::println("1. Matching Option with Some:");
    mana::Option<int32_t> opt1 = get_some();
    int32_t result1 = [&]() {
        auto __match_value_0 = opt1;
        if (__match_value_0.is_some()) {
            auto x = __match_value_0.unwrap();
            return (x * 2);
        }
        if (__match_value_0.is_none()) return 0;
    }();
    mana::print("  Result: ");
    mana::println(result1);
    mana::println();
    mana::println("2. Matching Option with None:");
    mana::Option<int32_t> opt2 = get_none();
    int32_t result2 = [&]() {
        auto __match_value_1 = opt2;
        if (__match_value_1.is_some()) {
            auto x = __match_value_1.unwrap();
            return (x * 2);
        }
        if (__match_value_1.is_none()) return (-1);
    }();
    mana::print("  Result: ");
    mana::println(result2);
    mana::println();
    mana::println("3. Matching Result with Ok:");
    mana::Result<int32_t, std::string> res1 = get_ok();
    int32_t result3 = [&]() {
        auto __match_value_2 = res1;
        if (__match_value_2.is_ok()) {
            auto v = __match_value_2.unwrap();
            return (v + 1);
        }
        if (__match_value_2.is_err()) {
            auto e = __match_value_2.unwrap_err();
            return 0;
        }
    }();
    mana::print("  Result: ");
    mana::println(result3);
    mana::println();
    mana::println("4. Matching Result with Err:");
    mana::Result<int32_t, std::string> res2 = get_err();
    int32_t result4 = [&]() {
        auto __match_value_3 = res2;
        if (__match_value_3.is_ok()) {
            auto v = __match_value_3.unwrap();
            return v;
        }
        if (__match_value_3.is_err()) {
            auto e = __match_value_3.unwrap_err();
            return (-99);
        }
    }();
    mana::print("  Result: ");
    mana::println(result4);
    mana::println();
    mana::println("=== All match pattern tests passed! ===");
    return 0;
}

