// Generated by mana-compiler from match_enum.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include "mana_runtime.h"

enum class Color {
    Red,
    Green,
    Blue
};

int32_t color_value(Color c) {
    return [&]() {
        auto __match_value_0 = c;
        if (__match_value_0 == Color::Red) return 100;
        if (__match_value_0 == Color::Green) return 200;
        if (__match_value_0 == Color::Blue) return 300;
        return 0;
    }();
}

int32_t main() {
    Color r = Color::Red;
    Color g = Color::Green;
    Color b = Color::Blue;
    mana::println(color_value(r));
    mana::println(color_value(g));
    mana::println(color_value(b));
    return 0;
}

