// Generated by mana-compiler from match.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include "mana_runtime.h"

int32_t main() {
    int32_t x = 2;
    int32_t result = [&]() {
        auto __match_value_0 = x;
        if (__match_value_0 == 1) return 10;
        if (__match_value_0 == 2) return 20;
        if (__match_value_0 == 3) return 30;
        return 0;
    }();
    mana::println(result);
    int32_t y = 5;
    int32_t doubled = [&]() {
        auto __match_value_1 = y;
        if (__match_value_1 == 1) return 2;
        if (__match_value_1 == 2) return 4;
        if (__match_value_1 == 5) return 10;
        return 0;
    }();
    mana::println(doubled);
    return result;
}

