// Generated by mana-compiler from C:/dev/mana-lang/examples/match_or_test.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include "mana_runtime.h"


int32_t main() {
    int32_t x = 2;
    std::string result = [&]() {
        auto __match_value_0 = x;
        if ((__match_value_0 == 1 || __match_value_0 == 2 || __match_value_0 == 3)) return "small";
        if ((__match_value_0 == 4 || __match_value_0 == 5)) return "medium";
        return "large";
    }();
    mana::println(result);
    return 0;
}

