// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    double x = 16.0;
    ([&]{ std::cout << "sqrt(16) = "; std::cout << mana::sqrt(x); std::cout << std::endl; }());
    double angle = 0.0;
    ([&]{ std::cout << "sin(0) = "; std::cout << mana::sin(angle); std::cout << std::endl; }());
    ([&]{ std::cout << "cos(0) = "; std::cout << mana::cos(angle); std::cout << std::endl; }());
    double val = 3.7;
    ([&]{ std::cout << "floor(3.7) = "; std::cout << mana::floor(val); std::cout << std::endl; }());
    ([&]{ std::cout << "ceil(3.7) = "; std::cout << mana::ceil(val); std::cout << std::endl; }());
    ([&]{ std::cout << "round(3.7) = "; std::cout << mana::round(val); std::cout << std::endl; }());
    ([&]{ std::cout << "log(2.718) = "; std::cout << mana::log(2.718); std::cout << std::endl; }());
    ([&]{ std::cout << "exp(1) = "; std::cout << mana::exp(1.0); std::cout << std::endl; }());
    ([&]{ std::cout << "pow(2, 10) = "; std::cout << mana::pow(2.0, 10.0); std::cout << std::endl; }());
    return 0;
}

