// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== Memory Safety Demo ===");
    int32_t counter = 0;
    mana::println(counter);
    counter = 1;
    mana::println(counter);
    counter = 2;
    mana::println(counter);
    int32_t value = 42;
    mana::println(value);
    mana::println("Done!");
    return 0;
}
