// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include "mana_runtime.h"

struct Point {
    int32_t x;
    int32_t y;
};

void print_point(const Point& p) {
    mana::print("Point(");
    mana::print(p.x);
    mana::print(", ");
    mana::print(p.y);
    mana::println(")");
}

void move_point(Point& p, int32_t dx, int32_t dy) {
    p.x = (p.x + dx);
    p.y = (p.y + dy);
}

int32_t main() {
    Point p = Point{.x = 10, .y = 20};
    mana::print("Initial: ");
    print_point(p);
    move_point(p, 5, 10);
    mana::print("After move: ");
    print_point(p);
    return 0;
}
