// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include "mana_runtime.h"

mana::Option<int32_t> get_some() {
    return mana::Some(42);
}

mana::Option<int32_t> get_none() {
    return mana::None;
}

int32_t main() {
    mana::println("=== None Keyword Test ===");
    mana::println();
    mana::println("1. Function returning None:");
    mana::Option<int32_t> opt = get_none();
    if (opt.is_some()) {
        auto v = opt.unwrap();
        mana::print("Got value: ");
        mana::println(v);
    } else     {
        mana::println("Got None (expected)");
    }

    mana::println();
    mana::println("2. Function returning Some:");
    mana::Option<int32_t> opt2 = get_some();
    if (opt2.is_some()) {
        auto v = opt2.unwrap();
        mana::print("Got value: ");
        mana::println(v);
    } else     {
        mana::println("Got None");
    }

    mana::println();
    mana::println("3. Direct None assignment:");
    mana::Option<int32_t> maybe = mana::None;
    if (maybe.is_some()) {
        auto v = maybe.unwrap();
        mana::print("Got: ");
        mana::println(v);
    } else     {
        mana::println("Value is None (expected)");
    }

    mana::println();
    mana::println("=== All None tests passed! ===");
    return 0;
}

