// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include "mana_runtime.h"

mana::Option<int32_t> get_some() {
    return mana::Some(42);
}

mana::Option<int32_t> get_none() {
    return mana::None;
}

mana::Option<std::string> get_some_string() {
    return mana::Some("hello");
}

mana::Option<std::string> get_none_string() {
    return mana::None;
}

int32_t main() {
    mana::println("=== Null Coalescing (??) Test ===");
    mana::println();
    mana::println("1. Null coalescing with Some:");
    int32_t val1 = [&]() -> std::decay_t<decltype(get_some().unwrap())> {
        auto __nc_0 = get_some();
        if (__nc_0.is_some()) return __nc_0.unwrap();
        return 0;
    }();
    mana::println((std::string("  get_some() ?? 0 = ") + mana::to_string(val1)));
    mana::println();
    mana::println("2. Null coalescing with None:");
    int32_t val2 = [&]() -> std::decay_t<decltype(get_none().unwrap())> {
        auto __nc_1 = get_none();
        if (__nc_1.is_some()) return __nc_1.unwrap();
        return 100;
    }();
    mana::println((std::string("  get_none() ?? 100 = ") + mana::to_string(val2)));
    mana::println();
    mana::println("3. String null coalescing with Some:");
    std::string str1 = [&]() -> std::decay_t<decltype(get_some_string().unwrap())> {
        auto __nc_2 = get_some_string();
        if (__nc_2.is_some()) return __nc_2.unwrap();
        return "default";
    }();
    mana::println((std::string("  get_some_string() ?? 'default' = ") + mana::to_string(str1)));
    mana::println();
    mana::println("4. String null coalescing with None:");
    std::string str2 = [&]() -> std::decay_t<decltype(get_none_string().unwrap())> {
        auto __nc_3 = get_none_string();
        if (__nc_3.is_some()) return __nc_3.unwrap();
        return "fallback";
    }();
    mana::println((std::string("  get_none_string() ?? 'fallback' = ") + mana::to_string(str2)));
    mana::println();
    mana::println("5. Direct inline usage:");
    int32_t val3 = [&]() -> std::decay_t<decltype(get_none().unwrap())> {
        auto __nc_4 = get_none();
        if (__nc_4.is_some()) return __nc_4.unwrap();
        return 999;
    }();
    mana::println((std::string("  get_none() ?? 999 = ") + mana::to_string(val3)));
    mana::println();
    mana::println("6. Null coalescing with inline Option:");
    mana::Option<int32_t> opt_some = mana::Some(77);
    mana::Option<int32_t> opt_none = mana::None;
    mana::println((std::string("  Some(77) ?? 0 = ") + mana::to_string([&]() -> std::decay_t<decltype(opt_some.unwrap())> {
        auto __nc_5 = opt_some;
        if (__nc_5.is_some()) return __nc_5.unwrap();
        return 0;
    }())));
    mana::println((std::string("  None ?? 123 = ") + mana::to_string([&]() -> std::decay_t<decltype(opt_none.unwrap())> {
        auto __nc_6 = opt_none;
        if (__nc_6.is_some()) return __nc_6.unwrap();
        return 123;
    }())));
    mana::println();
    mana::println("=== All null coalescing tests passed! ===");
    return 0;
}

