// Generated by mana-compiler from C:/dev/mana-lang/examples/octal_test.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== Octal Literal Test ===");
    mana::println();
    int32_t o1 = 8;
    int32_t o2 = 493;
    int32_t o3 = 511;
    int32_t o4 = 668;
    mana::print("0o10 = ");
    mana::println(o1);
    mana::print("0o755 = ");
    mana::println(o2);
    mana::print("0O777 = ");
    mana::println(o3);
    mana::print("0o12_34 = ");
    mana::println(o4);
    mana::println();
    mana::println("=== Octal literal tests passed! ===");
    return 0;
}

