// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include "mana_runtime.h"

struct Person {
    std::string name;
    int32_t age;
};

struct Container {
    int32_t value;
};

mana::Option<Person> get_person(bool has_person) {
    if (has_person) {
        return mana::Some(Person{.name = "Alice", .age = 30});
    }
    return mana::None;
}

mana::Option<Container> get_container(bool has_val) {
    if (has_val) {
        return mana::Some(Container{.value = 42});
    }
    return mana::None;
}

void print_opt_string(mana::Option<std::string> opt, std::string label) {
    if (opt.is_some()) {
        mana::println((std::string("  ") + mana::to_string(label) + std::string(" = ") + mana::to_string(opt.unwrap())));
    } else {
        mana::println((std::string("  ") + mana::to_string(label) + std::string(" = None")));
    }
}

void print_opt_int(mana::Option<int32_t> opt, std::string label) {
    if (opt.is_some()) {
        mana::println((std::string("  ") + mana::to_string(label) + std::string(" = ") + mana::to_string(opt.unwrap())));
    } else {
        mana::println((std::string("  ") + mana::to_string(label) + std::string(" = None")));
    }
}

int32_t main() {
    mana::println("=== Optional Chaining (?.) Test ===");
    mana::println();
    mana::println("1. Field access on Some:");
    mana::Option<Person> person_some = get_person(true);
    auto name_opt = [&]() {
        auto __opt_0 = person_some;
        if (__opt_0.is_none()) return mana::make_none<decltype(__opt_0.unwrap().name)>();
        return mana::Option<decltype(__opt_0.unwrap().name)>(mana::Some(__opt_0.unwrap().name));
    }();
    print_opt_string(name_opt, "person?.name");
    mana::println();
    mana::println("2. Field access on None:");
    mana::Option<Person> person_none = get_person(false);
    auto name_none = [&]() {
        auto __opt_1 = person_none;
        if (__opt_1.is_none()) return mana::make_none<decltype(__opt_1.unwrap().name)>();
        return mana::Option<decltype(__opt_1.unwrap().name)>(mana::Some(__opt_1.unwrap().name));
    }();
    print_opt_string(name_none, "person_none?.name");
    mana::println();
    mana::println("3. Numeric field access on Some:");
    mana::Option<Container> container_some = get_container(true);
    auto val_opt = [&]() {
        auto __opt_2 = container_some;
        if (__opt_2.is_none()) return mana::make_none<decltype(__opt_2.unwrap().value)>();
        return mana::Option<decltype(__opt_2.unwrap().value)>(mana::Some(__opt_2.unwrap().value));
    }();
    print_opt_int(val_opt, "container?.value");
    mana::println();
    mana::println("4. Numeric field on None:");
    mana::Option<Container> container_none = get_container(false);
    auto val_none = [&]() {
        auto __opt_3 = container_none;
        if (__opt_3.is_none()) return mana::make_none<decltype(__opt_3.unwrap().value)>();
        return mana::Option<decltype(__opt_3.unwrap().value)>(mana::Some(__opt_3.unwrap().value));
    }();
    print_opt_int(val_none, "container_none?.value");
    mana::println();
    mana::println("5. Age field access on Some:");
    auto age_opt = [&]() {
        auto __opt_4 = person_some;
        if (__opt_4.is_none()) return mana::make_none<decltype(__opt_4.unwrap().age)>();
        return mana::Option<decltype(__opt_4.unwrap().age)>(mana::Some(__opt_4.unwrap().age));
    }();
    print_opt_int(age_opt, "person?.age");
    mana::println();
    mana::println("=== All optional chaining tests passed! ===");
    return 0;
}

