// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include "mana_runtime.h"


struct Message_Move {
    int32_t _0;
    int32_t _1;
};

struct Message_Write {
    std::string text;
};

struct Message_ChangeColor {
    int32_t _0;
    int32_t _1;
    int32_t _2;
};

enum class MessageTag {
    Quit,
    Move,
    Write,
    ChangeColor
};

struct Message {
    MessageTag tag;
    std::variant<std::monostate, Message_Move, Message_Write, Message_ChangeColor> data;

    static Message Quit() {
        return Message{MessageTag::Quit, std::monostate{}};
    }
    static Message Move(int32_t v0, int32_t v1) {
        return Message{MessageTag::Move, Message_Move{v0, v1}};
    }
    static Message Write(std::string text) {
        return Message{MessageTag::Write, Message_Write{text}};
    }
    static Message ChangeColor(int32_t v0, int32_t v1, int32_t v2) {
        return Message{MessageTag::ChangeColor, Message_ChangeColor{v0, v1, v2}};
    }
};

enum class Status {
    Active,
    Inactive,
    Pending
};

std::string process_message(Message msg) {
    return [&]() {
        auto __match_value_0 = msg;
        if (__match_value_0.tag == MessageTag::Quit) {
            return (std::string("Received quit signal"));
        }
        if (__match_value_0.tag == MessageTag::Move) {
            auto __data_0 = std::get<Message_Move>(__match_value_0.data);
            auto x = __data_0._0;
            auto y = __data_0._1;
            return (std::string("Moving to (") + mana::to_string(x) + std::string(", ") + mana::to_string(y) + std::string(")"));
        }
        if (__match_value_0.tag == MessageTag::Write) {
            auto __data_0 = std::get<Message_Write>(__match_value_0.data);
            auto t = __data_0.text;
            return (std::string("Message: ") + mana::to_string(t));
        }
        if (__match_value_0.tag == MessageTag::ChangeColor) {
            auto __data_0 = std::get<Message_ChangeColor>(__match_value_0.data);
            auto r = __data_0._0;
            auto g = __data_0._1;
            auto b = __data_0._2;
            return (std::string("Color: rgb(") + mana::to_string(r) + std::string(", ") + mana::to_string(g) + std::string(", ") + mana::to_string(b) + std::string(")"));
        }
        return (std::string("Unknown message"));
    }();
}

int32_t get_displacement(Message msg) {
    return [&]() {
        auto __match_value_1 = msg;
        if (__match_value_1.tag == MessageTag::Move) {
            auto __data_1 = std::get<Message_Move>(__match_value_1.data);
            auto x = __data_1._0;
            auto y = __data_1._1;
            return (x + y);
        }
        return 0;
    }();
}

std::string status_to_string(Status s) {
    return [&]() {
        auto __match_value_2 = s;
        if (__match_value_2 == Status::Active) return (std::string("active"));
        if (__match_value_2 == Status::Inactive) return (std::string("inactive"));
        if (__match_value_2 == Status::Pending) return (std::string("pending"));
        return (std::string("unknown"));
    }();
}

int32_t main() {
    mana::println("=== Pattern Destructuring Test ===");
    mana::println();
    mana::println("1. Tuple variant destructuring:");
    Message move_msg = Message::Move(10, 20);
    mana::println((std::string("  ") + mana::to_string(process_message(move_msg))));
    mana::println("2. Struct variant destructuring:");
    Message write_msg = Message::Write("Hello, World!");
    mana::println((std::string("  ") + mana::to_string(process_message(write_msg))));
    mana::println("3. Unit variant:");
    Message quit_msg = Message::Quit();
    mana::println((std::string("  ") + mana::to_string(process_message(quit_msg))));
    mana::println("4. Triple tuple variant:");
    Message color_msg = Message::ChangeColor(255, 128, 0);
    mana::println((std::string("  ") + mana::to_string(process_message(color_msg))));
    mana::println("5. Displacement calculation:");
    Message move2 = Message::Move(5, 15);
    int32_t disp = get_displacement(move2);
    mana::println((std::string("  Displacement: ") + mana::to_string(disp)));
    mana::println("6. Simple enum matching:");
    Status status = Status::Active;
    mana::println((std::string("  Status: ") + mana::to_string(status_to_string(status))));
    mana::println();
    mana::println("=== All pattern tests passed! ===");
    return 0;
}

