// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include "mana_runtime.h"


struct Message_Move {
    int32_t _0;
    int32_t _1;
};

enum class MessageTag {
    Move,
    Quit
};

struct Message {
    MessageTag tag;
    std::variant<std::monostate, Message_Move> data;

    static Message Move(int32_t v0, int32_t v1) {
        return Message{MessageTag::Move, Message_Move{v0, v1}};
    }
    static Message Quit() {
        return Message{MessageTag::Quit, std::monostate{}};
    }
};

int32_t main() {
    Message msg = Message::Move(10, 20);
    int32_t result = [&]() {
        auto __match_value_0 = msg;
        if (__match_value_0.tag == MessageTag::Move) {
            auto __data_0 = std::get<Message_Move>(__match_value_0.data);
            auto x = __data_0._0;
            auto y = __data_0._1;
            return (x + y);
        }
        return 0;
    }();
    mana::print((std::string("Result: ") + mana::to_string(result)));
    return 0;
}

