// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== Power Operator Test ===");
    mana::println();
    double a = std::pow(2.0, 3.0);
    double b = std::pow(10.0, 2.0);
    double c = std::pow(2.0, 10.0);
    mana::print("2 ** 3 = ");
    mana::println(a);
    mana::print("10 ** 2 = ");
    mana::println(b);
    mana::print("2 ** 10 = ");
    mana::println(c);
    double d = std::pow(9.0, 0.5);
    mana::print("9 ** 0.5 = ");
    mana::println(d);
    double e = std::pow(2.0, (-1.0));
    mana::print("2 ** -1 = ");
    mana::println(e);
    double f = std::pow(2.0, std::pow(3.0, 2.0));
    mana::print("2 ** 3 ** 2 = ");
    mana::println(f);
    mana::println();
    mana::println("=== Power operator tests passed! ===");
    return 0;
}

