// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== Range Test ===");
    mana::println();
    mana::print("0..5: ");
    for (int32_t i = 0; i < 5; ++i)     {
        mana::print(i);
        mana::print(" ");
    }
    mana::println();
    mana::print("1..=5: ");
    for (int32_t i = 1; i <= 5; ++i)     {
        mana::print(i);
        mana::print(" ");
    }
    mana::println();
    mana::print("5..10: ");
    for (int32_t i = 5; i < 10; ++i)     {
        mana::print(i);
        mana::print(" ");
    }
    mana::println();
    mana::println();
    mana::println("=== Range tests passed! ===");
    return 0;
}

