// Generated by mana-compiler from C:/dev/mana-lang/examples/range_patterns.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include "mana_runtime.h"


std::string describe_number(int32_t n) {
    return [&]() {
        auto __match_value_0 = n;
        if ((__match_value_0 >= 1 && __match_value_0 <= 5)) return "very small";
        if ((__match_value_0 >= 6 && __match_value_0 <= 10)) return "small";
        if ((__match_value_0 >= 11 && __match_value_0 <= 50)) return "medium";
        if ((__match_value_0 >= 51 && __match_value_0 <= 100)) return "large";
        return "huge";
    }();
}

std::string grade_to_letter(int32_t score) {
    return [&]() {
        auto __match_value_1 = score;
        if ((__match_value_1 >= 90 && __match_value_1 <= 100)) return "A";
        if ((__match_value_1 >= 80 && __match_value_1 <= 89)) return "B";
        if ((__match_value_1 >= 70 && __match_value_1 <= 79)) return "C";
        if ((__match_value_1 >= 60 && __match_value_1 <= 69)) return "D";
        if ((__match_value_1 >= 0 && __match_value_1 <= 59)) return "F";
        return "Invalid";
    }();
}

int32_t main() {
    mana::println("=== Range Patterns Test ===");
    mana::println();
    mana::println("1. Inclusive range patterns (..=):");
    mana::println((std::string("  1 is ") + mana::to_string(describe_number(1))));
    mana::println((std::string("  5 is ") + mana::to_string(describe_number(5))));
    mana::println((std::string("  8 is ") + mana::to_string(describe_number(8))));
    mana::println((std::string("  25 is ") + mana::to_string(describe_number(25))));
    mana::println((std::string("  75 is ") + mana::to_string(describe_number(75))));
    mana::println((std::string("  150 is ") + mana::to_string(describe_number(150))));
    mana::println();
    mana::println("2. Grade conversion:");
    mana::println((std::string("  Score 95: ") + mana::to_string(grade_to_letter(95))));
    mana::println((std::string("  Score 85: ") + mana::to_string(grade_to_letter(85))));
    mana::println((std::string("  Score 72: ") + mana::to_string(grade_to_letter(72))));
    mana::println((std::string("  Score 65: ") + mana::to_string(grade_to_letter(65))));
    mana::println((std::string("  Score 45: ") + mana::to_string(grade_to_letter(45))));
    mana::println();
    mana::println("3. Range with other patterns:");
    int32_t special = 7;
    std::string result = [&]() {
        auto __match_value_2 = special;
        if ((__match_value_2 == 1 || __match_value_2 == 3 || __match_value_2 == 5 || __match_value_2 == 7 || __match_value_2 == 9)) return "odd single digit";
        if ((__match_value_2 == 2 || __match_value_2 == 4 || __match_value_2 == 6 || __match_value_2 == 8)) return "even single digit";
        if ((__match_value_2 >= 10 && __match_value_2 <= 99)) return "two digits";
        return "other";
    }();
    mana::println((std::string("  ") + mana::to_string(special) + std::string(" is ") + mana::to_string(result)));
    mana::println();
    mana::println("=== All range pattern tests passed! ===");
    return 0;
}

