// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    int32_t x = 7;
    std::string result = [&]() {
        auto __match_value_0 = x;
        if (((__match_value_0 >= 0 && __match_value_0 < 5))) return "small";
        if (((__match_value_0 >= 5 && __match_value_0 < 10))) return "medium";
        return "large";
    }();
    ([&]{ std::cout << "x="; std::cout << x; std::cout << ", result: "; std::cout << result; std::cout << std::endl; }());
    int32_t y = 5;
    std::string result2 = [&]() {
        auto __match_value_1 = y;
        if (((__match_value_1 >= 0 && __match_value_1 <= 4))) return "tiny";
        if (((__match_value_1 >= 5 && __match_value_1 <= 9))) return "small";
        return "other";
    }();
    ([&]{ std::cout << "y="; std::cout << y; std::cout << ", result2: "; std::cout << result2; std::cout << std::endl; }());
    return 0;
}

