// Generated by mana-compiler from C:/dev/mana-lang/examples/raw_string_test.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== Raw String Test ===");
    mana::println();
    std::string normal = "Hello\nWorld";
    mana::print("Normal string: ");
    mana::println(normal);
    std::string raw = "Hello\\nWorld";
    mana::print("Raw string: ");
    mana::println(raw);
    std::string path = "C:\\Users\\name\\Documents";
    mana::print("Windows path: ");
    mana::println(path);
    std::string regex = "\\d+\\.\\d+";
    mana::print("Regex pattern: ");
    mana::println(regex);
    mana::println();
    mana::println("=== Raw string tests passed! ===");
    return 0;
}

