// Generated by mana-compiler from C:/dev/mana-lang/examples/scientific_test.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== Scientific Notation Test ===");
    mana::println();
    double a = 1e10;
    double b = 1.5e3;
    double c = 2.5E-4;
    double d = 3e+2;
    mana::print("1e10 = ");
    mana::println(a);
    mana::print("1.5e3 = ");
    mana::println(b);
    mana::print("2.5E-4 = ");
    mana::println(c);
    mana::print("3e+2 = ");
    mana::println(d);
    mana::println();
    mana::println("=== Scientific notation tests passed! ===");
    return 0;
}

