// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== Slice Test ===");
    mana::println();
    mana::Vec<int32_t> numbers = {1, 2, 3, 4, 5};
    mana::print("Vec: ");
    for (int32_t i = 0; i < numbers.len(); ++i) {
        mana::print(numbers.at(i));
        mana::print(" ");
    }
    mana::println();
    auto first_num = mana::first(numbers);
    if (first_num.is_some()) {
        mana::print("First element: ");
        mana::println(first_num.unwrap());
    }
    auto last_num = mana::last(numbers);
    if (last_num.is_some()) {
        mana::print("Last element: ");
        mana::println(last_num.unwrap());
    }
    mana::Vec<int32_t> a = {1, 2, 3};
    mana::Vec<int32_t> b = {4, 5, 6};
    auto combined = mana::concat(a, b);
    mana::print("concat([1,2,3], [4,5,6]): ");
    for (int32_t i = 0; i < combined.len(); ++i) {
        mana::print(combined.at(i));
        mana::print(" ");
    }
    mana::println();
    mana::print("repeat(42, 4): ");
    auto repeated = mana::repeat(42, 4);
    for (int32_t i = 0; i < repeated.len(); ++i) {
        mana::print(repeated.at(i));
        mana::print(" ");
    }
    mana::println();
    mana::println();
    mana::println("Done!");
    return 0;
}

