// Generated by mana-compiler from C:/dev/mana-lang/examples/stdlib.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include "mana_runtime.h"

void test_vec() {
    mana::println("=== Vec<i32> ===");
    mana::Vec<int32_t> v = mana::Vec<int32_t>{};
    v.push(10);
    v.push(20);
    v.push(30);
    mana::print("Length: ");
    mana::println(v.len());
    mana::println("Elements:");
    for (auto val : v)     {
        mana::print(val);
        mana::print(" ");
    }
    mana::println();
    mana::Option<int32_t> popped = v.pop();
    if (popped.is_some())     {
        mana::print("Popped: ");
        mana::println(popped.unwrap());
    }
}

void test_string_funcs() {
    mana::println("=== String Functions ===");
    std::string s = "  Hello, World!  ";
    mana::print("Original: '");
    mana::print(s);
    mana::println("'");
    mana::print("Length: ");
    mana::println(mana::len(s));
    mana::print("Trimmed: '");
    mana::print(mana::trim(s));
    mana::println("'");
    std::string msg = "Hello, Mana!";
    if (mana::starts_with(msg, "Hello"))     {
        mana::println("Starts with 'Hello'");
    }
    if (mana::ends_with(msg, "!"))     {
        mana::println("Ends with '!'");
    }
    if (mana::contains(msg, "Mana"))     {
        mana::println("Contains 'Mana'");
    }
}

void test_math() {
    mana::println("=== Math Functions ===");
    int32_t x = (-42);
    mana::print("abs(-42) = ");
    mana::println(mana::abs(x));
    int32_t a = 10;
    int32_t b = 25;
    mana::print("min(10, 25) = ");
    mana::println(mana::min(a, b));
    mana::print("max(10, 25) = ");
    mana::println(mana::max(a, b));
    int32_t value = 50;
    mana::print("clamp(50, 0, 20) = ");
    mana::println(mana::clamp(value, 0, 20));
}

void test_to_string() {
    mana::println("=== to_string ===");
    int32_t num = 42;
    mana::print("to_string(42) = ");
    mana::println(mana::to_string(num));
    bool flag = true;
    mana::print("to_string(true) = ");
    mana::println(mana::to_string(flag));
}

int32_t main() {
    test_vec();
    mana::println();
    test_string_funcs();
    mana::println();
    test_math();
    mana::println();
    test_to_string();
    mana::println();
    mana::println("All tests passed!");
    return 0;
}

