// Generated by mana-compiler from C:/dev/mana-lang/examples/string_methods2.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include "mana_runtime.h"


int32_t main() {
    mana::println("=== String Methods Test ===");
    mana::println();
    mana::println("1. replace:");
    std::string text = "hello world world";
    auto replaced = mana::replace(text, "world", "mana");
    mana::println((std::string("  Original: ") + mana::to_string(text)));
    mana::println((std::string("  Replaced 'world' with 'mana': ") + mana::to_string(replaced)));
    mana::println();
    mana::println("2. Case conversion:");
    std::string mixed = "Hello World";
    auto upper = mana::to_uppercase(mixed);
    auto lower = mana::to_lowercase(mixed);
    mana::println((std::string("  Original: ") + mana::to_string(mixed)));
    mana::println((std::string("  Uppercase: ") + mana::to_string(upper)));
    mana::println((std::string("  Lowercase: ") + mana::to_string(lower)));
    mana::println();
    mana::println("3. split:");
    std::string csv = "apple,banana,cherry,date";
    auto parts = mana::split(csv, ",");
    mana::println((std::string("  Original: ") + mana::to_string(csv)));
    mana::println((std::string("  Split by ',': ") + mana::to_string(parts.len()) + std::string(" parts")));
    int32_t i = 0;
    while ((i < parts.len())) {
        mana::println((std::string("    [") + mana::to_string(i) + std::string("]: ") + mana::to_string(parts.at(i))));
        i = (i + 1);
    }
    mana::println();
    mana::println("4. join:");
    auto rejoined = mana::join(parts, " | ");
    mana::println((std::string("  Rejoined with ' | ': ") + mana::to_string(rejoined)));
    mana::println();
    mana::println("5. repeat:");
    std::string star = "*";
    auto stars = mana::repeat(star, 10);
    mana::println((std::string("  '*' repeated 10 times: ") + mana::to_string(stars)));
    mana::println();
    mana::println("6. reverse:");
    std::string forward = "hello";
    auto backward = mana::reverse(forward);
    mana::println((std::string("  Original: ") + mana::to_string(forward)));
    mana::println((std::string("  Reversed: ") + mana::to_string(backward)));
    mana::println();
    mana::println("7. Combined operations:");
    std::string sentence = "  The Quick Brown Fox  ";
    auto processed = mana::replace(mana::to_lowercase(mana::trim(sentence)), " ", "_");
    mana::println((std::string("  Original: '") + mana::to_string(sentence) + std::string("'")));
    mana::println((std::string("  Trimmed, lowercased, spaces to underscores: '") + mana::to_string(processed) + std::string("'")));
    mana::println();
    mana::println("=== All string method tests passed! ===");
    return 0;
}

