// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== String Method Test ===");
    mana::println();
    std::string s = "Hello, World!";
    int64_t len = s.size();
    mana::print("String: \"Hello, World!\" len = ");
    mana::println(len);
    std::string empty = "";
    mana::print("Empty string is_empty = ");
    mana::println(empty.empty());
    mana::print("Non-empty string is_empty = ");
    mana::println(s.empty());
    mana::println();
    mana::println("=== String method tests passed! ===");
    return 0;
}

