// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== String Methods Test ===");
    mana::println();
    std::string s = "Hello, World!";
    mana::print("Original: ");
    mana::println(s);
    mana::print("Uppercase: ");
    mana::println(mana::to_uppercase(s));
    mana::print("Lowercase: ");
    mana::println(mana::to_lowercase(s));
    mana::println();
    mana::print("Replace 'World' with 'Mana': ");
    mana::println(mana::replace(s, "World", "Mana"));
    mana::println();
    auto pos = mana::find(s, "World");
    if (pos.is_some()) {
        mana::print("Found 'World' at position: ");
        mana::println(pos.unwrap());
    }
    mana::println();
    std::string csv = "apple,banana,cherry";
    mana::print("CSV: ");
    mana::println(csv);
    auto parts = mana::split(csv, ",");
    mana::print("Split count: ");
    mana::println(parts.len());
    mana::print("Joined with ' - ': ");
    mana::println(mana::join(parts, " - "));
    mana::println();
    mana::print("'ab' repeated 5 times: ");
    mana::println(mana::repeat("ab", 5));
    mana::print("'Hello' reversed: ");
    mana::println(mana::reverse("Hello"));
    mana::println();
    mana::println("Done!");
    return 0;
}

