// Generated by mana-compiler from C:/dev/mana-lang/examples/string_split_test.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    std::string text = "apple,banana,cherry";
    mana::Vec<std::string> parts = mana::str_split(text, ",");
    mana::println("Split result:");
    for (int32_t i = 0; i < 3; ++i)     {
        mana::println(parts.at(i));
    }
    std::string joined = mana::str_join(parts, " - ");
    ([&]{ std::cout << "Joined: "; std::cout << joined; std::cout << std::endl; }());
    std::string hello = "Hello World";
    std::string upper = mana::str_to_upper(hello);
    std::string lower = mana::str_to_lower(hello);
    ([&]{ std::cout << "Upper: "; std::cout << upper; std::cout << std::endl; }());
    ([&]{ std::cout << "Lower: "; std::cout << lower; std::cout << std::endl; }());
    std::string star = "*";
    std::string stars = mana::str_repeat(star, 5);
    ([&]{ std::cout << "Stars: "; std::cout << stars; std::cout << std::endl; }());
    return 0;
}

