// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

struct Point {
    int32_t x;
    int32_t y;
};

void Point_print(Point& self) {
    mana::print("Point(");
    mana::print(self.x);
    mana::print(", ");
    mana::print(self.y);
    mana::println(")");
}

int32_t Point_magnitude_squared(Point& self) {
    return ((self.x * self.x) + (self.y * self.y));
}

Point Point_plus(Point& self, Point other) {
    return Point{.x = (self.x + other.x), .y = (self.y + other.y)};
}

int32_t main() {
    Point p1 = Point{.x = 3, .y = 4};
    Point p2 = Point{.x = 1, .y = 2};
    Point_print(p1);
    int32_t mag = Point_magnitude_squared(p1);
    mana::println(mag);
    Point p3 = Point_plus(p1, p2);
    Point_print(p3);
    return mag;
}

