// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include "mana_runtime.h"

std::tuple<int32_t, int32_t> get_point() {
    return std::make_tuple(10, 20);
}

std::tuple<std::string, int32_t, bool> get_person() {
    return std::make_tuple("Alice", 30, true);
}

int32_t main() {
    mana::println("=== Tuple Demo ===");
    mana::println();
    mana::println("1. Simple tuple:");
    std::tuple<int32_t, int32_t> point = std::make_tuple(100, 200);
    mana::print("x = ");
    mana::println(std::get<0>(point));
    mana::print("y = ");
    mana::println(std::get<1>(point));
    mana::println();
    mana::println("2. Tuple destructuring:");
    auto __ds_0 = get_point();
    auto x = std::get<0>(__ds_0);
    auto y = std::get<1>(__ds_0);
    mana::print("x = ");
    mana::println(x);
    mana::print("y = ");
    mana::println(y);
    mana::println();
    mana::println("3. Multi-element destructuring:");
    auto __ds_1 = get_person();
    auto name = std::get<0>(__ds_1);
    auto age = std::get<1>(__ds_1);
    auto active = std::get<2>(__ds_1);
    mana::print("name = ");
    mana::println(name);
    mana::print("age = ");
    mana::println(age);
    mana::print("active = ");
    mana::println(active);
    mana::println();
    mana::println("4. Inline destructuring:");
    auto __ds_2 = std::make_tuple(1, 2, 3);
    auto a = std::get<0>(__ds_2);
    auto b = std::get<1>(__ds_2);
    auto c = std::get<2>(__ds_2);
    mana::print("a = ");
    mana::println(a);
    mana::print("b = ");
    mana::println(b);
    mana::print("c = ");
    mana::println(c);
    mana::println();
    mana::println("5. Destructured values in expressions:");
    auto __ds_3 = std::make_tuple(640, 480);
    auto width = std::get<0>(__ds_3);
    auto height = std::get<1>(__ds_3);
    int32_t area = (width * height);
    mana::print("area = ");
    mana::println(area);
    mana::println();
    mana::println("=== All tuple tests passed! ===");
    return 0;
}
