// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include "mana_runtime.h"

using Int = int32_t;
using Float = float;
using Text = std::string;
using IntOption = mana::Option<int32_t>;
using IntVec = mana::Vec<int32_t>;
int32_t main() {
    mana::println("=== Type Alias Test ===");
    mana::println();
    Int x = 42;
    Float y = 3.14;
    Text s = "Hello, type aliases!";
    mana::print("Int value: ");
    mana::println(x);
    mana::print("Float value: ");
    mana::println(y);
    mana::print("Text value: ");
    mana::println(s);
    mana::println();
    IntOption opt = mana::Some(100);
    if (opt.is_some()) {
        auto v = opt.unwrap();
        mana::print("IntOption value: ");
        mana::println(v);
    }
    mana::println();
    IntVec vec = mana::Vec<int32_t>{};
    vec.push(1);
    vec.push(2);
    vec.push(3);
    mana::print("IntVec length: ");
    mana::println(vec.len());
    mana::println();
    mana::println("=== Type alias tests passed! ===");
    return 0;
}

