// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include "mana_runtime.h"

using UserId = int32_t;
using Score = double;
using Name = std::string;
using IntVec = mana::Vec<int32_t>;
using StringOption = mana::Option<std::string>;

struct User {
    UserId id;
    Name name;
    Score score;
};

User create_user(UserId id, Name name) {
    return User{.id = id, .name = name, .score = 0.0};
}

UserId get_user_id(User user) {
    return user.id;
}

StringOption get_optional_name(bool has_name) {
    if (has_name) {
        return mana::Some("Alice");
    }
    return mana::None;
}

int32_t main() {
    mana::println("=== Type Aliases Test ===");
    mana::println();
    mana::println("1. Basic type aliases:");
    UserId user_id = 42;
    Score score = 95.5;
    Name name = "Bob";
    mana::println((std::string("  UserId: ") + mana::to_string(user_id)));
    mana::println((std::string("  Score: ") + mana::to_string(score)));
    mana::println((std::string("  Name: ") + mana::to_string(name)));
    mana::println();
    mana::println("2. Struct with type aliases:");
    User user = create_user(123, "Charlie");
    mana::println((std::string("  User ID: ") + mana::to_string(user.id)));
    mana::println((std::string("  User Name: ") + mana::to_string(user.name)));
    mana::println((std::string("  User Score: ") + mana::to_string(user.score)));
    mana::println();
    mana::println("3. Function with type alias return:");
    UserId id = get_user_id(user);
    mana::println((std::string("  Retrieved ID: ") + mana::to_string(id)));
    mana::println();
    mana::println("4. Generic type alias defined (IntVec = Vec<i32>)");
    mana::println();
    mana::println("5. Option type alias:");
    StringOption opt_name = get_optional_name(true);
    if (opt_name.is_some()) {
        mana::println((std::string("  Got name: ") + mana::to_string(opt_name.unwrap())));
    }
    StringOption no_name = get_optional_name(false);
    if (no_name.is_none()) {
        mana::println("  No name (None)");
    }
    mana::println();
    mana::println("=== All type alias tests passed! ===");
    return 0;
}

