// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== Underscore Numeric Separator Test ===");
    mana::println();
    int32_t million = 1000000;
    int32_t thousands = 123456789;
    mana::print("1_000_000 = ");
    mana::println(million);
    mana::print("123_456_789 = ");
    mana::println(thousands);
    mana::println();
    float pi = 3.141592;
    double large_float = 1000000.123456;
    mana::print("3.14_15_92 = ");
    mana::println(pi);
    mana::print("1_000_000.123_456 = ");
    mana::println(large_float);
    mana::println();
    mana::println("=== Underscore tests passed! ===");
    return 0;
}

