// Generated by mana-compiler from C:/dev/mana-lang/examples/vec_method_test2.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    mana::Vec<int32_t> numbers = {1, 2, 3, 4, 5};
    int32_t total = mana::vec_sum(numbers);
    ([&]{ std::cout << "sum: "; std::cout << total; std::cout << std::endl; }());
    mana::Vec<int32_t> reversed = mana::vec_reverse(numbers);
    mana::println("reversed:");
    for (int32_t i = 0; i < 5; ++i)     {
        ([&]{ std::cout << reversed.at(i); std::cout << std::endl; }());
    }
    mana::Vec<int32_t> first_three = mana::vec_take(numbers, 3);
    mana::println("first 3:");
    for (int32_t i = 0; i < 3; ++i)     {
        ([&]{ std::cout << first_three.at(i); std::cout << std::endl; }());
    }
    return 0;
}

