// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== Vec Method Test ===");
    mana::println();
    mana::Vec<int32_t> v = {1, 2, 3, 4, 5};
    mana::print("Initial length: ");
    mana::println(v.len());
    v.push(6);
    v.push(7);
    mana::print("After push 6, 7 length: ");
    mana::println(v.len());
    mana::print("Element at index 0: ");
    mana::println(v.at(0));
    mana::print("Element at index 6: ");
    mana::println(v.at(6));
    mana::print("Is empty: ");
    mana::println(v.is_empty());
    v.pop();
    mana::print("After pop length: ");
    mana::println(v.len());
    mana::println();
    mana::println("=== Vec method tests passed! ===");
    return 0;
}

