// Generated by mana-compiler from C:/dev/mana-lang/examples/whilelet.mana
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include "mana_runtime.h"

int32_t main() {
    mana::println("=== while-let Demo ===");
    mana::println();
    mana::println("1. while let Some with Vec pop:");
    mana::Vec<int32_t> vec = mana::Vec<int32_t>{};
    vec.push(1);
    vec.push(2);
    vec.push(3);
    vec.push(4);
    vec.push(5);
    mana::print("Popping: ");
    while (true) {
        auto __wl_0 = vec.pop();
        if (!__wl_0.is_some()) break;
        auto value = __wl_0.unwrap();
        mana::print(value);
        mana::print(" ");
    }
    mana::println();
    mana::println();
    mana::println("2. Counting down:");
    mana::Vec<int32_t> vec2 = mana::Vec<int32_t>{};
    vec2.push(10);
    vec2.push(20);
    vec2.push(30);
    while (true) {
        auto __wl_1 = vec2.pop();
        if (!__wl_1.is_some()) break;
        auto n = __wl_1.unwrap();
        mana::print("Got: ");
        mana::println(n);
    }
    mana::println();
    mana::println("3. Early break:");
    mana::Vec<int32_t> vec3 = mana::Vec<int32_t>{};
    vec3.push(1);
    vec3.push(2);
    vec3.push(100);
    vec3.push(3);
    vec3.push(4);
    while (true) {
        auto __wl_2 = vec3.pop();
        if (!__wl_2.is_some()) break;
        auto x = __wl_2.unwrap();
        if ((x > 50))         {
            mana::println("Found large value, stopping");
            break;
        }
        mana::print("Small value: ");
        mana::println(x);
    }
    mana::println();
    mana::println("=== All while-let tests passed! ===");
    return 0;
}

