// Generated by mana-compiler from demo.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"


#include "mana_graphics.h"

int64_t create_window(std::string title, int32_t width, int32_t height);
bool window_open(int64_t window);
void clear(float r, float g, float b);
void present(int64_t window);
void close_window(int64_t window);
double get_time();
int32_t create_shader(std::string vertex_src, std::string fragment_src);
void use_shader(int32_t program);
int32_t create_triangle();
void draw_triangle(int32_t vao);

int64_t create_window(std::string title, int32_t width, int32_t height) {
    if ((mana_glfwInit() == 0)) {
        mana::println("Failed to initialize GLFW");
        return 0;
    }
    int64_t window = mana_glfwCreateWindow(width, height, title, 0, 0);
    if ((window == 0)) {
        mana::println("Failed to create window");
        mana_glfwTerminate();
        return 0;
    }
    mana_glfwMakeContextCurrent(window);
    if ((mana_gladLoadGL() == 0)) {
        mana::println("Failed to load OpenGL");
        mana_glfwDestroyWindow(window);
        mana_glfwTerminate();
        return 0;
    }
    mana_glfwSwapInterval(1);
    mana_glViewport(0, 0, width, height);
    return window;
}

bool window_open(int64_t window) {
    return (mana_glfwWindowShouldClose(window) == 0);
}

void clear(float r, float g, float b) {
    mana_glClearColor(r, g, b, 1.0);
    mana_glClear(mana_GL_COLOR_BUFFER_BIT());
}

void present(int64_t window) {
    mana_glfwSwapBuffers(window);
    mana_glfwPollEvents();
}

void close_window(int64_t window) {
    mana_glfwDestroyWindow(window);
    mana_glfwTerminate();
}

double get_time() {
    return mana_glfwGetTime();
}

int32_t create_shader(std::string vertex_src, std::string fragment_src) {
    int32_t vs = mana_glCreateShader(mana_GL_VERTEX_SHADER());
    mana_glShaderSource(vs, vertex_src);
    mana_glCompileShader(vs);
    if ((mana_glGetShaderiv(vs, mana_GL_COMPILE_STATUS()) == 0)) {
        mana_glGetShaderInfoLog(vs);
        return 0;
    }
    int32_t fs = mana_glCreateShader(mana_GL_FRAGMENT_SHADER());
    mana_glShaderSource(fs, fragment_src);
    mana_glCompileShader(fs);
    if ((mana_glGetShaderiv(fs, mana_GL_COMPILE_STATUS()) == 0)) {
        mana_glGetShaderInfoLog(fs);
        return 0;
    }
    int32_t program = mana_glCreateProgram();
    mana_glAttachShader(program, vs);
    mana_glAttachShader(program, fs);
    mana_glLinkProgram(program);
    mana_glDeleteShader(vs);
    mana_glDeleteShader(fs);
    return program;
}

void use_shader(int32_t program) {
    mana_glUseProgram(program);
}

int32_t create_triangle() {
    int32_t vao = mana_glGenVertexArray();
    mana_glBindVertexArray(vao);
    mana_createTriangleVBO();
    mana_setupTriangleAttributes();
    return vao;
}

void draw_triangle(int32_t vao) {
    mana_glBindVertexArray(vao);
    mana_glDrawArrays(mana_GL_TRIANGLES(), 0, 3);
}

int32_t main() {
    int64_t window = create_window("Mana Demo", 800, 600);
    if ((window == 0)) {
        return 1;
    }
    std::string vs = "#version 330 core\nlayout (location = 0) in vec3 aPos;\nlayout (location = 1) in vec3 aColor;\nout vec3 vertexColor;\nvoid main() { gl_Position = vec4(aPos, 1.0); vertexColor = aColor; }";
    std::string fs = "#version 330 core\nin vec3 vertexColor;\nout vec4 FragColor;\nvoid main() { FragColor = vec4(vertexColor, 1.0); }";
    int32_t shader = create_shader(vs, fs);
    int32_t triangle = create_triangle();
    while (window_open(window)) {
        clear(0.1, 0.1, 0.15);
        use_shader(shader);
        draw_triangle(triangle);
        present(window);
    }
    close_window(window);
    return 0;
}

