// Generated by mana-compiler from examples/graphics/triangle.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"
#include "mana_graphics.h"


std::string get_vertex_shader();
std::string get_fragment_shader();
int32_t compile_shader(std::string source, int32_t shader_type);
int32_t create_shader_program(std::string vertex_src, std::string fragment_src);

std::string get_vertex_shader() {
    return "#version 330 core\nlayout (location = 0) in vec3 aPos;\nlayout (location = 1) in vec3 aColor;\nout vec3 vertexColor;\nvoid main() {\n    gl_Position = vec4(aPos, 1.0);\n    vertexColor = aColor;\n}";
}

std::string get_fragment_shader() {
    return "#version 330 core\nin vec3 vertexColor;\nout vec4 FragColor;\nvoid main() {\n    FragColor = vec4(vertexColor, 1.0);\n}";
}

int32_t compile_shader(std::string source, int32_t shader_type) {
    int32_t shader = mana_glCreateShader(shader_type);
    mana_glShaderSource(shader, source);
    mana_glCompileShader(shader);
    int32_t success = mana_glGetShaderiv(shader, mana_GL_COMPILE_STATUS());
    if ((success == 0)) {
        mana::println("Shader compilation failed!");
        mana_glGetShaderInfoLog(shader);
        return 0;
    }
    return shader;
}

int32_t create_shader_program(std::string vertex_src, std::string fragment_src) {
    int32_t vertex_shader = compile_shader(vertex_src, mana_GL_VERTEX_SHADER());
    if ((vertex_shader == 0)) {
        return 0;
    }
    int32_t fragment_shader = compile_shader(fragment_src, mana_GL_FRAGMENT_SHADER());
    if ((fragment_shader == 0)) {
        mana_glDeleteShader(vertex_shader);
        return 0;
    }
    int32_t program = mana_glCreateProgram();
    mana_glAttachShader(program, vertex_shader);
    mana_glAttachShader(program, fragment_shader);
    mana_glLinkProgram(program);
    int32_t success = mana_glGetProgramiv(program, mana_GL_LINK_STATUS());
    if ((success == 0)) {
        mana::println("Shader program linking failed!");
        mana_glGetProgramInfoLog(program);
        mana_glDeleteShader(vertex_shader);
        mana_glDeleteShader(fragment_shader);
        return 0;
    }
    mana_glDeleteShader(vertex_shader);
    mana_glDeleteShader(fragment_shader);
    return program;
}

int32_t main() {
    mana::println("Mana Triangle Demo - OpenGL Shader Pipeline");
    mana::println("============================================");
    if ((mana_glfwInit() == 0)) {
        mana::println("Failed to initialize GLFW");
        return 1;
    }
    int64_t window = mana_glfwCreateWindow(800, 600, "Mana Triangle Demo", 0, 0);
    if ((window == 0)) {
        mana::println("Failed to create window");
        mana_glfwTerminate();
        return 1;
    }
    mana_glfwMakeContextCurrent(window);
    if ((mana_gladLoadGL() == 0)) {
        mana::println("Failed to load OpenGL");
        mana_glfwDestroyWindow(window);
        mana_glfwTerminate();
        return 1;
    }
    mana_glfwSwapInterval(1);
    mana_glViewport(0, 0, 800, 600);
    mana::println("OpenGL loaded successfully!");
    int32_t shader_program = create_shader_program(get_vertex_shader(), get_fragment_shader());
    if ((shader_program == 0)) {
        mana::println("Failed to create shader program");
        mana_glfwDestroyWindow(window);
        mana_glfwTerminate();
        return 1;
    }
    mana::println("Shader program created!");
    int32_t vao = mana_glGenVertexArray();
    mana_glBindVertexArray(vao);
    int32_t vbo = mana_createTriangleVBO();
    mana_setupTriangleAttributes();
    mana::println("Triangle geometry created!");
    mana::println("Starting render loop...");
    while ((mana_glfwWindowShouldClose(window) == 0)) {
        mana_glClearColor(0.1, 0.1, 0.1, 1.0);
        mana_glClear(mana_GL_COLOR_BUFFER_BIT());
        mana_glUseProgram(shader_program);
        mana_glBindVertexArray(vao);
        mana_glDrawArrays(mana_GL_TRIANGLES(), 0, 3);
        mana_glfwSwapBuffers(window);
        mana_glfwPollEvents();
    }
    mana::println("Cleaning up...");
    mana_glDeleteVertexArray(vao);
    mana_glDeleteBuffer(vbo);
    mana_glDeleteProgram(shader_program);
    mana_glfwDestroyWindow(window);
    mana_glfwTerminate();
    mana::println("Done!");
    return 0;
}

