// Generated by mana-compiler from examples/graphics/voxel.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"


#include "mana_graphics.h"

int64_t create_window(std::string title, int32_t width, int32_t height);
bool window_open(int64_t window);
void clear(float r, float g, float b);
void present(int64_t window);
void close_window(int64_t window);
double get_time();
int32_t create_shader(std::string vertex_src, std::string fragment_src);
void use_shader(int32_t program);
int32_t create_triangle();
void draw_triangle(int32_t vao);
bool key_pressed(int64_t window, int32_t key);
bool mouse_pressed(int64_t window, int32_t button);
void clear_3d(float r, float g, float b);

int64_t create_window(std::string title, int32_t width, int32_t height) {
    if ((mana_glfwInit() == 0)) {
        mana::println("Failed to initialize GLFW");
        return 0;
    }
    int64_t window = mana_glfwCreateWindow(width, height, title, 0, 0);
    if ((window == 0)) {
        mana::println("Failed to create window");
        mana_glfwTerminate();
        return 0;
    }
    mana_glfwMakeContextCurrent(window);
    if ((mana_gladLoadGL() == 0)) {
        mana::println("Failed to load OpenGL");
        mana_glfwDestroyWindow(window);
        mana_glfwTerminate();
        return 0;
    }
    mana_glfwSwapInterval(1);
    mana_glViewport(0, 0, width, height);
    return window;
}

bool window_open(int64_t window) {
    return (mana_glfwWindowShouldClose(window) == 0);
}

void clear(float r, float g, float b) {
    mana_glClearColor(r, g, b, 1.0);
    mana_glClear(mana_GL_COLOR_BUFFER_BIT());
}

void present(int64_t window) {
    mana_glfwSwapBuffers(window);
    mana_glfwPollEvents();
}

void close_window(int64_t window) {
    mana_glfwDestroyWindow(window);
    mana_glfwTerminate();
}

double get_time() {
    return mana_glfwGetTime();
}

int32_t create_shader(std::string vertex_src, std::string fragment_src) {
    int32_t vs = mana_glCreateShader(mana_GL_VERTEX_SHADER());
    mana_glShaderSource(vs, vertex_src);
    mana_glCompileShader(vs);
    if ((mana_glGetShaderiv(vs, mana_GL_COMPILE_STATUS()) == 0)) {
        mana_glGetShaderInfoLog(vs);
        return 0;
    }
    int32_t fs = mana_glCreateShader(mana_GL_FRAGMENT_SHADER());
    mana_glShaderSource(fs, fragment_src);
    mana_glCompileShader(fs);
    if ((mana_glGetShaderiv(fs, mana_GL_COMPILE_STATUS()) == 0)) {
        mana_glGetShaderInfoLog(fs);
        return 0;
    }
    int32_t program = mana_glCreateProgram();
    mana_glAttachShader(program, vs);
    mana_glAttachShader(program, fs);
    mana_glLinkProgram(program);
    mana_glDeleteShader(vs);
    mana_glDeleteShader(fs);
    return program;
}

void use_shader(int32_t program) {
    mana_glUseProgram(program);
}

int32_t create_triangle() {
    int32_t vao = mana_glGenVertexArray();
    mana_glBindVertexArray(vao);
    mana_createTriangleVBO();
    mana_setupTriangleAttributes();
    return vao;
}

void draw_triangle(int32_t vao) {
    mana_glBindVertexArray(vao);
    mana_glDrawArrays(mana_GL_TRIANGLES(), 0, 3);
}

bool key_pressed(int64_t window, int32_t key) {
    return (mana_glfwGetKey(window, key) == mana_GLFW_PRESS());
}

bool mouse_pressed(int64_t window, int32_t button) {
    return (mana_glfwGetMouseButton(window, button) == mana_GLFW_PRESS());
}

void clear_3d(float r, float g, float b) {
    mana_glClearColor(r, g, b, 1.0);
    mana_glClear((mana_GL_COLOR_BUFFER_BIT() + mana_GL_DEPTH_BUFFER_BIT()));
}

int32_t main() {
    int64_t window = create_window("Mana Voxel - Click to capture mouse, TAB to release, WASD move, ESC quit", 1024, 768);
    if ((window == 0)) {
        return 1;
    }
    std::string vs = "#version 330 core\nlayout (location = 0) in vec3 aPos;\nlayout (location = 1) in vec3 aColor;\nuniform mat4 uMVP;\nout vec3 vertexColor;\nvoid main() { gl_Position = uMVP * vec4(aPos, 1.0); vertexColor = aColor; }";
    std::string fs = "#version 330 core\nin vec3 vertexColor;\nout vec4 FragColor;\nvoid main() { FragColor = vec4(vertexColor, 1.0); }";
    int32_t shader = create_shader(vs, fs);
    int32_t mvpLoc = mana_glGetUniformLocation(shader, "uMVP");
    int32_t grassVao = mana_glGenVertexArray();
    mana_glBindVertexArray(grassVao);
    mana_createBlockVBO(0);
    mana_setupCubeAttributes();
    int32_t dirtVao = mana_glGenVertexArray();
    mana_glBindVertexArray(dirtVao);
    mana_createBlockVBO(1);
    mana_setupCubeAttributes();
    int32_t stoneVao = mana_glGenVertexArray();
    mana_glBindVertexArray(stoneVao);
    mana_createBlockVBO(2);
    mana_setupCubeAttributes();
    int32_t waterVao = mana_glGenVertexArray();
    mana_glBindVertexArray(waterVao);
    mana_createBlockVBO(3);
    mana_setupCubeAttributes();
    int32_t sandVao = mana_glGenVertexArray();
    mana_glBindVertexArray(sandVao);
    mana_createBlockVBO(4);
    mana_setupCubeAttributes();
    mana_glEnable(mana_GL_DEPTH_TEST());
    mana_glEnable(mana_GL_CULL_FACE());
    mana_setPerspective(70.0, 1.333, 0.1, 100.0);
    float camX = 4.5;
    float camY = 8.0;
    float camZ = 12.0;
    float camYaw = 0.0;
    float camPitch = -0.29999999999999999;
    float moveSpeed = 0.080000000000000002;
    float mouseSens = 0.0030000000000000001;
    int32_t worldSize = 9;
    int32_t waterLevel = 1;
    mana::println("Mana Voxel World");
    mana::println("Controls:");
    mana::println("  Click - Capture mouse for free look");
    mana::println("  TAB - Release mouse");
    mana::println("  WASD - Move");
    mana::println("  Q/E - Move up/down");
    mana::println("  Space - Reset position");
    mana::println("  ESC - Quit");
    while (window_open(window)) {
        if (key_pressed(window, mana_GLFW_KEY_ESCAPE())) {
            break;
        }
        if (key_pressed(window, mana_GLFW_KEY_TAB())) {
            mana_releaseMouse(window);
        }
        if (mouse_pressed(window, mana_GLFW_MOUSE_BUTTON_LEFT())) {
            if ((mana_isMouseCaptured() == 0)) {
                mana_captureMouse(window);
            }
        }
        if ((mana_isMouseCaptured() == 1)) {
            mana_updateMouseDelta(window);
            float deltaX = mana_getMouseDeltaX();
            float deltaY = mana_getMouseDeltaY();
            camYaw = (camYaw + (deltaX * mouseSens));
            camPitch = (camPitch + (deltaY * mouseSens));
        }
        if ((camPitch > 1.5)) {
            camPitch = 1.5;
        }
        if ((camPitch < -1.5)) {
            camPitch = (-1.5);
        }
        float fwdX = mana_getForwardX();
        float fwdZ = mana_getForwardZ();
        float rightX = mana_getRightX();
        float rightZ = mana_getRightZ();
        if (key_pressed(window, mana_GLFW_KEY_W())) {
            camX = (camX + (fwdX * moveSpeed));
            camZ = (camZ + (fwdZ * moveSpeed));
        }
        if (key_pressed(window, mana_GLFW_KEY_S())) {
            camX = (camX - (fwdX * moveSpeed));
            camZ = (camZ - (fwdZ * moveSpeed));
        }
        if (key_pressed(window, mana_GLFW_KEY_A())) {
            camX = (camX - (rightX * moveSpeed));
            camZ = (camZ - (rightZ * moveSpeed));
        }
        if (key_pressed(window, mana_GLFW_KEY_D())) {
            camX = (camX + (rightX * moveSpeed));
            camZ = (camZ + (rightZ * moveSpeed));
        }
        if (key_pressed(window, mana_GLFW_KEY_Q())) {
            camY = (camY - moveSpeed);
        }
        if (key_pressed(window, mana_GLFW_KEY_E())) {
            camY = (camY + moveSpeed);
        }
        if (key_pressed(window, mana_GLFW_KEY_SPACE())) {
            camX = 4.5;
            camY = 8.0;
            camZ = 12.0;
            camYaw = 0.0;
            camPitch = (-0.3);
        }
        mana_setCameraFPS(camX, camY, camZ, camYaw, camPitch);
        clear_3d(0.5, 0.7, 1.0);
        use_shader(shader);
{
            int32_t x = 0;
            while ((x < worldSize)) {
{
                    int32_t z = 0;
                    while ((z < worldSize)) {
                        int32_t terrainHeight = mana_getTerrainHeight(x, z);
{
                            int32_t y = 0;
                            while ((y <= terrainHeight)) {
                                float px = (x * 1.0);
                                float py = (y * 1.0);
                                float pz = (z * 1.0);
                                mana_setModelPosition(px, py, pz);
                                mana_glUniformMatrix4fv(mvpLoc, mana_getMVP());
                                if ((y == terrainHeight)) {
                                    if ((terrainHeight <= waterLevel)) {
                                        mana_glBindVertexArray(sandVao);
                                    } else {
                                        mana_glBindVertexArray(grassVao);
                                    }
                                } else {
                                    if ((y > (terrainHeight - 3))) {
                                        mana_glBindVertexArray(dirtVao);
                                    } else {
                                        mana_glBindVertexArray(stoneVao);
                                    }
                                }
                                mana_drawCube();
                                y = (y + 1);
                            }
                        }                        if ((terrainHeight < waterLevel)) {
{
                                int32_t y = (terrainHeight + 1);
                                while ((y <= waterLevel)) {
                                    float px = (x * 1.0);
                                    float py = (y * 1.0);
                                    float pz = (z * 1.0);
                                    mana_setModelPosition(px, py, pz);
                                    mana_glUniformMatrix4fv(mvpLoc, mana_getMVP());
                                    mana_glBindVertexArray(waterVao);
                                    mana_drawCube();
                                    y = (y + 1);
                                }
                            }                        }
                        if ((terrainHeight > (waterLevel + 1))) {
                            if ((mana_shouldPlaceTree(x, z) == 1)) {
                                int32_t trunkHeight = 3;
{
                                    int32_t ty = 1;
                                    while ((ty <= trunkHeight)) {
                                        float px = (x * 1.0);
                                        float py = ((terrainHeight + ty) * 1.0);
                                        float pz = (z * 1.0);
                                        mana_setModelPosition(px, py, pz);
                                        mana_glUniformMatrix4fv(mvpLoc, mana_getMVP());
                                        mana_glBindVertexArray(dirtVao);
                                        mana_drawCube();
                                        ty = (ty + 1);
                                    }
                                }                                float leafY = (((terrainHeight + trunkHeight) + 1) * 1.0);
                                mana_setModelPosition((x * 1.0), leafY, (z * 1.0));
                                mana_glUniformMatrix4fv(mvpLoc, mana_getMVP());
                                mana_glBindVertexArray(grassVao);
                                mana_drawCube();
                            }
                        }
                        z = (z + 1);
                    }
                }                x = (x + 1);
            }
        }        present(window);
    }
    close_window(window);
    return 0;
}

