// Generated by mana-compiler from examples/graphics/window.mana
// Generated by mana-compiler
#include <cstdint>
#include <string>
#include <array>
#include <vector>
#include <tuple>
#include <cmath>
#include <type_traits>
#include <variant>
#include <future>
#include "mana_runtime.h"
#include "mana_graphics.h"


int32_t main() {
    if ((mana_glfwInit() == 0)) {
        mana::println("Failed to initialize GLFW");
        return 1;
    }
    int64_t window = mana_glfwCreateWindow(800, 600, "Mana Graphics Demo", 0, 0);
    if ((window == 0)) {
        mana::println("Failed to create window");
        mana_glfwTerminate();
        return 1;
    }
    mana_glfwMakeContextCurrent(window);
    if ((mana_gladLoadGL() == 0)) {
        mana::println("Failed to load OpenGL");
        mana_glfwDestroyWindow(window);
        mana_glfwTerminate();
        return 1;
    }
    mana_glfwSwapInterval(1);
    mana_glViewport(0, 0, 800, 600);
    mana::println("Window created! Starting render loop...");
    while ((mana_glfwWindowShouldClose(window) == 0)) {
        double time = mana_glfwGetTime();
        float r = static_cast<float>((0.5 + (0.5 * std::sin(time))));
        float g = static_cast<float>((0.5 + (0.5 * std::sin((time + 2.0)))));
        float b = static_cast<float>((0.5 + (0.5 * std::sin((time + 4.0)))));
        mana_glClearColor(r, g, b, 1.0);
        mana_glClear(16384);
        mana_glfwSwapBuffers(window);
        mana_glfwPollEvents();
    }
    mana::println("Shutting down...");
    mana_glfwDestroyWindow(window);
    mana_glfwTerminate();
    return 0;
}

